import {
    HERO_IMAGE1,
    HERO_IMAGE2,
    HERO_IMAGE3,
    HERO_IMAGE4,
    HERO_IMAGE5,
    HERO_IMAGE6,
    HERO_IMAGE7,
    HERO_IMAGE8,
    HERO_IMAGE9,
    HERO_IMAGE10,
    HERO_IMAGE11,
    HERO_IMAGE12,
    HERO_IMAGE13,
    HERO_IMAGE14,
    HERO_IMAGE15,
    HERO_IMAGE16,
} from "@/constants/images";

const packages = [
    {
        id: 1,
        title: "Big Five Safari",
        desc: "Witness lions, leopards, elephants, rhinos, and buffalos in natural habitat.",
        image: HERO_IMAGE1,
        link: "/big-five-safari",
        linkText: "Book Now",
        location: "Kruger National Park, South Africa",
        rating: 4.9,
        offprice: "800",
        reviews: 410,
        price: "620",
        duration: "6 Days – 5 Nights",
        feature: "Big Five"
    },
    {
        id: 2,
        title: "Tiger Trail Expedition",
        desc: "Follow tiger pawprints through dense forests and remote riverbanks.",
        image: HERO_IMAGE2,
        link: "/tiger-trail-expedition",
        linkText: "Book Now",
        location: "Bandhavgarh, India",
        rating: 4.7,
        reviews: 285,
        offprice: "15% off",
        price: "480",
        duration: "4 Days – 3 Nights",
        feature: "Tiger Territory"
    },
    {
        id: 3,
        title: "Elephant Reserve Safari",
        desc: "Spend days watching majestic elephants roam free in their herds.",
        image: HERO_IMAGE3,
        link: "/elephant-reserve-safari",
        linkText: "Book Now",
        location: "Udawalawe, Sri Lanka",
        rating: 4.6,
        reviews: 175,
        price: "360",
        duration: "3 Days – 2 Nights",
        feature: "Family Friendly"
    },
    {
        id: 4,
        title: "Leopard Hills Safari",
        desc: "Spot elusive leopards lounging in trees or stalking across grasslands.",
        image: HERO_IMAGE4,
        link: "/leopard-hills",
        linkText: "Book Now",
        location: "Yala, Sri Lanka",
        rating: 4.8,
        reviews: 210,
        price: "420",
        duration: "4 Days – 3 Nights",
        feature: "Photographer’s Choice"
    },
    {
        id: 5,
        title: "Kaziranga Rhino Safari",
        desc: "Ride into grasslands to see the rare one-horned rhino roaming freely.",
        image: HERO_IMAGE5,
        link: "/kaziranga-rhino-safari",
        linkText: "Book Now",
        location: "Kaziranga, India",
        rating: 4.6,
        reviews: 193,
        price: "400",
        duration: "3 Days – 2 Nights",
        feature: "UNESCO Reserve"
    },
    {
        id: 6,
        title: "Lion Kingdom Safari",
        desc: "Watch lion prides rule the savannahs in thrilling sunrise game drives.",
        image: HERO_IMAGE6,
        link: "/lion-kingdom",
        linkText: "Book Now",
        location: "Masai Mara, Kenya",
        rating: 4.9,
        reviews: 450,
        price: "650",
        duration: "5 Days – 4 Nights",
        feature: "Popular"
    },
    {
        id: 7,
        title: "Swamp Safari Experience",
        desc: "Cruise crocodile-infested waters with binoculars ready for rare birds.",
        image: HERO_IMAGE7,
        link: "/swamp-safari",
        linkText: "Book Now",
        location: "Sundarbans, India",
        rating: 4.5,
        reviews: 178,
        price: "390",
        duration: "3 Days – 2 Nights",
        feature: "Mangrove Trek"
    },
    {
        id: 8,
        title: "Desert Fox Safari",
        desc: "Explore desert plains where foxes, caracals, and hyenas roam freely.",
        image: HERO_IMAGE8,
        link: "/desert-fox-safari",
        linkText: "Book Now",
        location: "Rann of Kutch, India",
        rating: 4.3,
        reviews: 120,
        price: "310",
        duration: "2 Days – 1 Night",
        feature: "Offbeat"
    },
    {
        id: 9,
        title: "Rainforest Wildlife Trek",
        desc: "Trek through misty rainforests echoing with bird calls and monkey chatter.",
        image: HERO_IMAGE9,
        link: "/rainforest-trek",
        linkText: "Book Now",
        location: "Western Ghats, India",
        rating: 4.7,
        reviews: 230,
        price: "450",
        duration: "4 Days – 3 Nights",
        feature: "Eco Adventure"
    },
    {
        id: 10,
        title: "Nocturnal Night Safari",
        desc: "Witness wild nightlife with glowing eyes and nocturnal predator hunts.",
        image: HERO_IMAGE10,
        link: "/night-safari",
        linkText: "Book Now",
        location: "Gir National Park, India",
        rating: 4.4,
        reviews: 165,
        price: "320",
        duration: "2 Days – 1 Night",
        feature: "Night Ride"
    },
    {
        id: 11,
        title: "Cheetah Plains Safari",
        desc: "Speed across grasslands following the fastest predator on Earth.",
        image: HERO_IMAGE11,
        link: "/cheetah-plains",
        linkText: "Book Now",
        location: "Okavango Delta, Botswana",
        rating: 4.9,
        reviews: 270,
        price: "700",
        duration: "5 Days – 4 Nights",
        feature: "Speed Chase"
    },
    {
        id: 12,
        title: "Hornbill Jungle Safari",
        desc: "Track rare hornbills, gibbons, and reptiles in deep forest interiors.",
        image: HERO_IMAGE12,
        link: "/hornbill-jungle-safari",
        linkText: "Book Now",
        location: "Pakke Tiger Reserve, India",
        rating: 4.5,
        reviews: 142,
        price: "340",
        duration: "3 Days – 2 Nights",
        feature: "Birdwatcher Pick"
    },
    {
        id: 13,
        title: "Canyon Wildlife Walk",
        desc: "Walk among cliffs and caves spotting wild goats, jackals, and eagles.",
        image: HERO_IMAGE13,
        link: "/canyon-wildlife-walk",
        linkText: "Book Now",
        location: "Satpura, India",
        rating: 4.4,
        reviews: 160,
        price: "390",
        duration: "4 Days – 3 Nights",
        feature: "Guided Hike"
    },
    {
        id: 14,
        title: "Snow Leopard Quest",
        desc: "Join high-altitude experts to track the rare snow leopard silently.",
        image: HERO_IMAGE14,
        link: "/snow-leopard-quest",
        linkText: "Book Now",
        location: "Hemis National Park, India",
        rating: 4.8,
        reviews: 195,
        price: "750",
        duration: "6 Days – 5 Nights",
        feature: "Rare Sightings"
    },
    {
        id: 15,
        title: "Forest Canopy Drive",
        desc: "Drive under treetop tunnels with howler monkeys swinging above.",
        image: HERO_IMAGE15,
        link: "/forest-canopy-drive",
        linkText: "Book Now",
        location: "Periyar Wildlife Sanctuary, India",
        rating: 4.5,
        reviews: 180,
        price: "370",
        duration: "3 Days – 2 Nights",
        feature: "Scenic Ride"
    },
    {
        id: 16,
        title: "Wetland Safari Escape",
        desc: "Explore shallow waters and grass patches brimming with storks and deer.",
        image: HERO_IMAGE16,
        link: "/wetland-escape",
        linkText: "Book Now",
        location: "Keoladeo Ghana, India",
        rating: 4.6,
        reviews: 210,
        price: "400",
        duration: "3 Days – 2 Nights",
        feature: "Bird Sanctuary"
    }
];

export default packages;