// 108+ Curated Authentic Safari Expeditions
const packages = [
  {
    "id": 1,
    "title": "Serengeti Great Migration & Mara River Crossing",
    "desc": "Private 4x4 open safari tracking 1.5 million wildebeest river crossings, apex lions, and cheetah coalitions across the Seronera Valley.",
    "image": "/assets/images/destinations/serengeti-national-park.jpg",
    "link": "/packages/serengeti-national-park",
    "linkText": "Book Expedition",
    "location": "Serengeti National Park, Tanzania",
    "rating": 4.9,
    "reviews": 420,
    "offprice": "10% off",
    "price": "650",
    "duration": "6 Days – 5 Nights",
    "feature": "Great Migration",
    "slug": "serengeti-national-park"
  },
  {
    "id": 2,
    "title": "Maasai Mara Apex Predator & Hot Air Balloon Trail",
    "desc": "Dawn hot air balloon voyage over the Mara river followed by off-road tracking of Marsh Pride lions, leopards, and black rhinos.",
    "image": "/assets/images/destinations/maasai-mara-reserve.jpg",
    "link": "/packages/maasai-mara-reserve",
    "linkText": "Book Expedition",
    "location": "Maasai Mara National Reserve, Kenya",
    "rating": 4.9,
    "reviews": 380,
    "offprice": "15% off",
    "price": "620",
    "duration": "5 Days – 4 Nights",
    "feature": "Big Five",
    "slug": "maasai-mara-reserve"
  },
  {
    "id": 3,
    "title": "Greater Kruger & Sabi Sand Luxury Big 5 Safari",
    "desc": "Exclusive private concession drives with night thermal spot-lighting, tracking elusive leopards, white rhinos, and wild dog packs.",
    "image": "/assets/images/destinations/kruger-national-park.jpg",
    "link": "/packages/kruger-national-park",
    "linkText": "Book Expedition",
    "location": "Kruger National Park, South Africa",
    "rating": 4.8,
    "reviews": 310,
    "offprice": null,
    "price": "590",
    "duration": "5 Days – 4 Nights",
    "feature": "Big Five",
    "slug": "kruger-national-park"
  },
  {
    "id": 4,
    "title": "Okavango Delta Mokoro & Predator Trail",
    "desc": "Glide along crystalline water channels by traditional mokoro canoe and private 4x4 vehicles across Moremi Game Reserve and Chief's Island.",
    "image": "/assets/images/destinations/okavango-delta.jpg",
    "link": "/packages/okavango-delta",
    "linkText": "Book Expedition",
    "location": "Okavango Delta, Botswana",
    "rating": 4.9,
    "reviews": 290,
    "offprice": "15% off",
    "price": "700",
    "duration": "6 Days – 5 Nights",
    "feature": "Delta Oasis",
    "slug": "okavango-delta"
  },
  {
    "id": 5,
    "title": "Ngorongoro Crater Lost World Expedition",
    "desc": "Crater-floor game drives encountering dense lion prides, flamingos on Lake Magadi, and ancient Olduvai Gorge anthropological sites.",
    "image": "/assets/images/destinations/ngorongoro-crater.jpg",
    "link": "/packages/ngorongoro-crater",
    "linkText": "Book Expedition",
    "location": "Ngorongoro Conservation Area, Tanzania",
    "rating": 4.9,
    "reviews": 260,
    "offprice": "10% off",
    "price": "680",
    "duration": "4 Days – 3 Nights",
    "feature": "UNESCO Reserve",
    "slug": "ngorongoro-crater"
  },
  {
    "id": 6,
    "title": "Chobe Riverfront & Savuti Elephant Odyssey",
    "desc": "Dual boat and 4x4 safaris capturing massive elephant bathings and the famed Savuti marsh lion prides.",
    "image": "/assets/images/destinations/chobe-national-park.jpg",
    "link": "/packages/chobe-national-park",
    "linkText": "Book Expedition",
    "location": "Chobe National Park, Botswana",
    "rating": 4.8,
    "reviews": 215,
    "offprice": null,
    "price": "580",
    "duration": "4 Days – 3 Nights",
    "feature": "Elephant Haven",
    "slug": "chobe-national-park"
  },
  {
    "id": 7,
    "title": "Amboseli Kilimanjaro Tusker & Photography Safari",
    "desc": "Capture iconic wide-angle photos of giant elephant herds with snow-capped Mount Kilimanjaro as your backdrop.",
    "image": "/assets/images/destinations/amboseli-national-park.jpg",
    "link": "/packages/amboseli-national-park",
    "linkText": "Book Expedition",
    "location": "Amboseli National Park, Kenya",
    "rating": 4.8,
    "reviews": 195,
    "offprice": "10% off",
    "price": "540",
    "duration": "4 Days – 3 Nights",
    "feature": "Photography Escort",
    "slug": "amboseli-national-park"
  },
  {
    "id": 8,
    "title": "Etosha Salt Pan & Desert Wildlife Circuit",
    "desc": "Floodlit night waterhole vigils watching endangered black rhinos and lion prides congregate in dramatic desert terrain.",
    "image": "/assets/images/destinations/etosha-national-park.jpg",
    "link": "/packages/etosha-national-park",
    "linkText": "Book Expedition",
    "location": "Etosha National Park, Namibia",
    "rating": 4.8,
    "reviews": 180,
    "offprice": null,
    "price": "610",
    "duration": "5 Days – 4 Nights",
    "feature": "Desert Wilderness",
    "slug": "etosha-national-park"
  },
  {
    "id": 9,
    "title": "South Luangwa Valley of the Leopard Walking Safari",
    "desc": "Intimate on-foot guided tracking through prime leopard territory with seasoned Zambian bush naturalists.",
    "image": "/assets/images/destinations/south-luangwa-national-park.jpg",
    "link": "/packages/south-luangwa-national-park",
    "linkText": "Book Expedition",
    "location": "South Luangwa National Park, Zambia",
    "rating": 4.9,
    "reviews": 210,
    "offprice": "15% off",
    "price": "670",
    "duration": "6 Days – 5 Nights",
    "feature": "Walking Safari",
    "slug": "south-luangwa-national-park"
  },
  {
    "id": 10,
    "title": "Mana Pools Zambezi Canoe & Walking Trail",
    "desc": "Thrilling canoe safaris down the Lower Zambezi and walking alongside iconic bull elephants.",
    "image": "/assets/images/destinations/mana-pools-zimbabwe.jpg",
    "link": "/packages/mana-pools-zimbabwe",
    "linkText": "Book Expedition",
    "location": "Mana Pools National Park, Zimbabwe",
    "rating": 4.9,
    "reviews": 175,
    "offprice": "15% off",
    "price": "720",
    "duration": "5 Days – 4 Nights",
    "feature": "Walking Safari",
    "slug": "mana-pools-zimbabwe"
  },
  {
    "id": 11,
    "title": "Samburu Special Five & Ewaso River Safari",
    "desc": "Discover northern Kenya's unique endemic species with native Samburu warrior trackers.",
    "image": "/assets/images/destinations/samburu-national-reserve.jpg",
    "link": "/packages/samburu-national-reserve",
    "linkText": "Book Expedition",
    "location": "Samburu National Reserve, Kenya",
    "rating": 4.8,
    "reviews": 160,
    "offprice": "10% off",
    "price": "570",
    "duration": "4 Days – 3 Nights",
    "feature": "Specialist Wildlife",
    "slug": "samburu-national-reserve"
  },
  {
    "id": 12,
    "title": "Hwange Waterhole Hides & Predator Vigils",
    "desc": "Sit at eye level with hundreds of drinking elephants inside custom sunken photography hides.",
    "image": "/assets/images/destinations/hwange-national-park.jpg",
    "link": "/packages/hwange-national-park",
    "linkText": "Book Expedition",
    "location": "Hwange National Park, Zimbabwe",
    "rating": 4.8,
    "reviews": 185,
    "offprice": null,
    "price": "590",
    "duration": "5 Days – 4 Nights",
    "feature": "Big Five",
    "slug": "hwange-national-park"
  },
  {
    "id": 13,
    "title": "Tarangire Baobabs & Giant Elephant Herds",
    "desc": "Scenic safaris amid ancient baobabs tracking dense dry-season elephant gatherings and tree-climbing lions.",
    "image": "/assets/images/destinations/tarangire-national-park.jpg",
    "link": "/packages/tarangire-national-park",
    "linkText": "Book Expedition",
    "location": "Tarangire National Park, Tanzania",
    "rating": 4.7,
    "reviews": 150,
    "offprice": "10% off",
    "price": "530",
    "duration": "3 Days – 2 Nights",
    "feature": "Elephant Haven",
    "slug": "tarangire-national-park"
  },
  {
    "id": 14,
    "title": "Lake Nakuru Pink Flamingo & Rhino Sanctuary",
    "desc": "Rift valley photographic circuit combining flamingo lakeshores with high-probability rhino sightings.",
    "image": "/assets/images/destinations/lake-nakuru-national-park.jpg",
    "link": "/packages/lake-nakuru-national-park",
    "linkText": "Book Expedition",
    "location": "Lake Nakuru National Park, Kenya",
    "rating": 4.7,
    "reviews": 140,
    "offprice": null,
    "price": "480",
    "duration": "3 Days – 2 Nights",
    "feature": "Bird Sanctuary",
    "slug": "lake-nakuru-national-park"
  },
  {
    "id": 15,
    "title": "Ishasha Tree Lions & Kazinga Boat Safari",
    "desc": "Search for lions lounging high in fig trees and cruise alongside hundreds of hippos on the Kazinga Channel.",
    "image": "/assets/images/destinations/queen-elizabeth-national-park.jpg",
    "link": "/packages/queen-elizabeth-national-park",
    "linkText": "Book Expedition",
    "location": "Queen Elizabeth National Park, Uganda",
    "rating": 4.8,
    "reviews": 170,
    "offprice": "15% off",
    "price": "560",
    "duration": "4 Days – 3 Nights",
    "feature": "Big Five",
    "slug": "queen-elizabeth-national-park"
  },
  {
    "id": 16,
    "title": "Madikwe Luxury Family & Wild Dog Safari",
    "desc": "Malaria-free 5-star lodge experience with specialized junior ranger tracking programs and wild dog packs.",
    "image": "/assets/images/destinations/madikwe-game-reserve.jpg",
    "link": "/packages/madikwe-game-reserve",
    "linkText": "Book Expedition",
    "location": "Madikwe Game Reserve, South Africa",
    "rating": 4.9,
    "reviews": 190,
    "offprice": "10% off",
    "price": "630",
    "duration": "4 Days – 3 Nights",
    "feature": "Family Friendly",
    "slug": "madikwe-game-reserve"
  },
  {
    "id": 17,
    "title": "Phinda Seven Habitats & Cheetah Conservation Quest",
    "desc": "Join reserve researchers on monitoring runs tracking cheetah coalitions and rare black rhinos.",
    "image": "/assets/images/destinations/phinda-private-game-reserve.jpg",
    "link": "/packages/phinda-private-game-reserve",
    "linkText": "Book Expedition",
    "location": "Phinda Private Game Reserve, South Africa",
    "rating": 4.9,
    "reviews": 205,
    "offprice": "15% off",
    "price": "760",
    "duration": "5 Days – 4 Nights",
    "feature": "Conservation Tour",
    "slug": "phinda-private-game-reserve"
  },
  {
    "id": 18,
    "title": "Sabi Sand Ultimate Leopard & Big Five Luxury Safari",
    "desc": "Ultra-luxury open vehicle safaris with off-roading permits to follow leopards through dense riverine bush.",
    "image": "/assets/images/destinations/sabi-sand-game-reserve.jpg",
    "link": "/packages/sabi-sand-game-reserve",
    "linkText": "Book Expedition",
    "location": "Sabi Sand Game Reserve, South Africa",
    "rating": 5,
    "reviews": 360,
    "offprice": "10% off",
    "price": "880",
    "duration": "5 Days – 4 Nights",
    "feature": "Big Five",
    "slug": "sabi-sand-game-reserve"
  },
  {
    "id": 19,
    "title": "Tsavo Red Elephant & Mzima Springs Expedition",
    "desc": "Discover the rugged lava landscapes of Tsavo and observe hippos underwater at crystal Mzima Springs.",
    "image": "/assets/images/destinations/tsavo-national-parks.jpg",
    "link": "/packages/tsavo-national-parks",
    "linkText": "Book Expedition",
    "location": "Tsavo East & West National Parks, Kenya",
    "rating": 4.7,
    "reviews": 165,
    "offprice": null,
    "price": "510",
    "duration": "4 Days – 3 Nights",
    "feature": "Elephant Haven",
    "slug": "tsavo-national-parks"
  },
  {
    "id": 20,
    "title": "Moremi Chief's Island Predator & Boat Expedition",
    "desc": "Camp on remote islands in Moremi with daily 4x4 game drives and boat channels teeming with wildlife.",
    "image": "/assets/images/destinations/moremi-game-reserve.jpg",
    "link": "/packages/moremi-game-reserve",
    "linkText": "Book Expedition",
    "location": "Moremi Game Reserve, Botswana",
    "rating": 4.9,
    "reviews": 230,
    "offprice": "15% off",
    "price": "740",
    "duration": "5 Days – 4 Nights",
    "feature": "Delta Oasis",
    "slug": "moremi-game-reserve"
  },
  {
    "id": 21,
    "title": "Lower Zambezi Canoe & Luxury Bush Safari",
    "desc": "Silent canoe drifts along the Zambezi riverbanks combined with open 4x4 night predator tracking.",
    "image": "/assets/images/destinations/lower-zambezi-national-park.jpg",
    "link": "/packages/lower-zambezi-national-park",
    "linkText": "Book Expedition",
    "location": "Lower Zambezi National Park, Zambia",
    "rating": 4.9,
    "reviews": 190,
    "offprice": "10% off",
    "price": "690",
    "duration": "5 Days – 4 Nights",
    "feature": "River Expedition",
    "slug": "lower-zambezi-national-park"
  },
  {
    "id": 22,
    "title": "Busanga Plains Wild Lion & Cheetah Circuit",
    "desc": "Venture deep into the remote Busanga Plains to spot mist-shrouded lion prides and roaming cheetahs.",
    "image": "/assets/images/destinations/kafue-national-park.jpg",
    "link": "/packages/kafue-national-park",
    "linkText": "Book Expedition",
    "location": "Kafue National Park, Zambia",
    "rating": 4.8,
    "reviews": 155,
    "offprice": null,
    "price": "660",
    "duration": "6 Days – 5 Nights",
    "feature": "Offbeat Safari",
    "slug": "kafue-national-park"
  },
  {
    "id": 23,
    "title": "Liuwa Plain Wildebeest Migration & Hyena Quest",
    "desc": "Witness Africa's secret wildebeest migration and clan dynamics in one of the continent's most remote plains.",
    "image": "/assets/images/destinations/liuwa-plain-national-park.jpg",
    "link": "/packages/liuwa-plain-national-park",
    "linkText": "Book Expedition",
    "location": "Liuwa Plain National Park, Zambia",
    "rating": 4.9,
    "reviews": 130,
    "offprice": "15% off",
    "price": "780",
    "duration": "5 Days – 4 Nights",
    "feature": "Great Migration",
    "slug": "liuwa-plain-national-park"
  },
  {
    "id": 24,
    "title": "Gonarezhou Chilojo Cliffs & Elephant Wilderness",
    "desc": "Scenic 4x4 expedition beneath towering crimson cliffs tracking wild elephant corridors.",
    "image": "/assets/images/destinations/gonarezhou-national-park.jpg",
    "link": "/packages/gonarezhou-national-park",
    "linkText": "Book Expedition",
    "location": "Gonarezhou National Park, Zimbabwe",
    "rating": 4.8,
    "reviews": 140,
    "offprice": null,
    "price": "620",
    "duration": "5 Days – 4 Nights",
    "feature": "Offbeat Safari",
    "slug": "gonarezhou-national-park"
  },
  {
    "id": 25,
    "title": "Hluhluwe-iMfolozi Rhino Conservation Trail",
    "desc": "Explore the cradle of rhino conservation with specialized rhino tracking rangers across Zulu hills.",
    "image": "/assets/images/destinations/hluhluwe-imfolozi-park.jpg",
    "link": "/packages/hluhluwe-imfolozi-park",
    "linkText": "Book Expedition",
    "location": "Hluhluwe-iMfolozi Park, South Africa",
    "rating": 4.8,
    "reviews": 170,
    "offprice": "10% off",
    "price": "520",
    "duration": "4 Days – 3 Nights",
    "feature": "Conservation Tour",
    "slug": "hluhluwe-imfolozi-park"
  },
  {
    "id": 26,
    "title": "Addo 'Big Seven' Bush to Coast Safari",
    "desc": "Unique overland expedition combining bush tracking of 600+ elephants with coastal marine boat trips for whales and sharks.",
    "image": "/assets/images/destinations/addo-elephant-national-park.jpg",
    "link": "/packages/addo-elephant-national-park",
    "linkText": "Book Expedition",
    "location": "Addo Elephant National Park, South Africa",
    "rating": 4.8,
    "reviews": 195,
    "offprice": null,
    "price": "490",
    "duration": "4 Days – 3 Nights",
    "feature": "Big Five",
    "slug": "addo-elephant-national-park"
  },
  {
    "id": 27,
    "title": "Timbavati White Lion & Big 5 Tracking Odyssey",
    "desc": "Search for rare white lion prides and enjoy star-bed sleepouts under the Southern African night sky.",
    "image": "/assets/images/destinations/timbavati-game-reserve.jpg",
    "link": "/packages/timbavati-game-reserve",
    "linkText": "Book Expedition",
    "location": "Timbavati Private Nature Reserve, South Africa",
    "rating": 4.9,
    "reviews": 210,
    "offprice": "15% off",
    "price": "790",
    "duration": "5 Days – 4 Nights",
    "feature": "Rare Species",
    "slug": "timbavati-game-reserve"
  },
  {
    "id": 28,
    "title": "Kidepo Valley Lost Eden Wilderness Safari",
    "desc": "Fly-in safari to Uganda's most scenic wilderness encountering vast buffalo herds and Karimojong cultural villages.",
    "image": "/assets/images/destinations/kidepo-valley-national-park.jpg",
    "link": "/packages/kidepo-valley-national-park",
    "linkText": "Book Expedition",
    "location": "Kidepo Valley National Park, Uganda",
    "rating": 4.9,
    "reviews": 145,
    "offprice": "10% off",
    "price": "650",
    "duration": "4 Days – 3 Nights",
    "feature": "Offbeat Safari",
    "slug": "kidepo-valley-national-park"
  },
  {
    "id": 29,
    "title": "Nyerere Rufiji River Boat & Walking Safari",
    "desc": "Boat safaris on Lake Manze and Rufiji river channels watching bathing elephants and hunting wild dogs.",
    "image": "/assets/images/destinations/selous-nyerere-national-park.jpg",
    "link": "/packages/selous-nyerere-national-park",
    "linkText": "Book Expedition",
    "location": "Nyerere National Park (Selous), Tanzania",
    "rating": 4.8,
    "reviews": 180,
    "offprice": null,
    "price": "620",
    "duration": "4 Days – 3 Nights",
    "feature": "River Expedition",
    "slug": "selous-nyerere-national-park"
  },
  {
    "id": 30,
    "title": "Ruaha Super-Pride Lions & Baobab Wilderness",
    "desc": "Track giant lion prides of 20+ members hunting buffalo along the dry sand rivers of Ruaha.",
    "image": "/assets/images/destinations/ruaha-national-park.jpg",
    "link": "/packages/ruaha-national-park",
    "linkText": "Book Expedition",
    "location": "Ruaha National Park, Tanzania",
    "rating": 4.9,
    "reviews": 195,
    "offprice": "15% off",
    "price": "640",
    "duration": "5 Days – 4 Nights",
    "feature": "Big Five",
    "slug": "ruaha-national-park"
  },
  {
    "id": 31,
    "title": "Bandhavgarh Royal Bengal Tiger Quest",
    "desc": "Explore the core tiger territories of Tala, Magdhi, and Khitauli with senior naturalists and dawn pugmark tracking.",
    "image": "/assets/images/destinations/bandhavgarh-tiger-reserve.jpg",
    "link": "/packages/bandhavgarh-tiger-reserve",
    "linkText": "Book Expedition",
    "location": "Bandhavgarh National Park, India",
    "rating": 4.9,
    "reviews": 320,
    "offprice": "15% off",
    "price": "480",
    "duration": "5 Days – 4 Nights",
    "feature": "Tiger Dynasty",
    "slug": "bandhavgarh-tiger-reserve"
  },
  {
    "id": 32,
    "title": "Kaziranga Great Rhino & Brahmaputra Safari",
    "desc": "Venture through the tall elephant grass of Kohora and Bagori ranges to encounter prehistoric rhinos and wild buffalo.",
    "image": "/assets/images/destinations/kaziranga-rhino-sanctuary.jpg",
    "link": "/packages/kaziranga-rhino-sanctuary",
    "linkText": "Book Expedition",
    "location": "Kaziranga National Park, India",
    "rating": 4.8,
    "reviews": 240,
    "offprice": "10% off",
    "price": "420",
    "duration": "4 Days – 3 Nights",
    "feature": "UNESCO Sanctuary",
    "slug": "kaziranga-rhino-sanctuary"
  },
  {
    "id": 33,
    "title": "Ranthambore Fortress Tiger & Lake Zones Safari",
    "desc": "Custom open 4x4 Gypsy safaris covering premier zones 1-5 around Rajbagh and Malik lakes.",
    "image": "/assets/images/destinations/ranthambore-national-park.jpg",
    "link": "/packages/ranthambore-national-park",
    "linkText": "Book Expedition",
    "location": "Ranthambore National Park, India",
    "rating": 4.8,
    "reviews": 350,
    "offprice": "15% off",
    "price": "460",
    "duration": "4 Days – 3 Nights",
    "feature": "Tiger Territory",
    "slug": "ranthambore-national-park"
  },
  {
    "id": 34,
    "title": "Kanha Kipling Wilderness & Barasingha Trail",
    "desc": "Traverse the sweeping Mukki and Kanha meadows tracking wild tiger prides and packs of Asiatic wild dogs.",
    "image": "/assets/images/destinations/kanha-national-park.jpg",
    "link": "/packages/kanha-national-park",
    "linkText": "Book Expedition",
    "location": "Kanha National Park, India",
    "rating": 4.9,
    "reviews": 280,
    "offprice": null,
    "price": "470",
    "duration": "5 Days – 4 Nights",
    "feature": "Tiger Territory",
    "slug": "kanha-national-park"
  },
  {
    "id": 35,
    "title": "Corbett Dhikala Core & Ramganga River Safari",
    "desc": "Stay inside the historic Dhikala rest house overlooking the Ramganga reservoir with morning and evening elephant corridor drives.",
    "image": "/assets/images/destinations/jim-corbett-national-park.jpg",
    "link": "/packages/jim-corbett-national-park",
    "linkText": "Book Expedition",
    "location": "Jim Corbett National Park, India",
    "rating": 4.8,
    "reviews": 290,
    "offprice": "10% off",
    "price": "430",
    "duration": "4 Days – 3 Nights",
    "feature": "Heritage Safari",
    "slug": "jim-corbett-national-park"
  },
  {
    "id": 36,
    "title": "Tadoba Tiger Dynasty & Waterhole Safari",
    "desc": "Full-day safari permits tracking dominant tigresses and their active cubs across Moharli and Kolara gates.",
    "image": "/assets/images/destinations/tadoba-andhari-reserve.jpg",
    "link": "/packages/tadoba-andhari-reserve",
    "linkText": "Book Expedition",
    "location": "Tadoba Andhari Tiger Reserve, India",
    "rating": 4.9,
    "reviews": 310,
    "offprice": "20% off",
    "price": "450",
    "duration": "4 Days – 3 Nights",
    "feature": "Tiger Dynasty",
    "slug": "tadoba-andhari-reserve"
  },
  {
    "id": 37,
    "title": "Gir Forest Asiatic Lion Sanctuary Trail",
    "desc": "Encounter royal Asiatic lions in their only wild homeland with seasoned Gujarati forest trackers.",
    "image": "/assets/images/destinations/gir-lion-sanctuary.jpg",
    "link": "/packages/gir-lion-sanctuary",
    "linkText": "Book Expedition",
    "location": "Gir National Park & Sanctuary, India",
    "rating": 4.8,
    "reviews": 230,
    "offprice": null,
    "price": "410",
    "duration": "3 Days – 2 Nights",
    "feature": "Rare Species",
    "slug": "gir-lion-sanctuary"
  },
  {
    "id": 38,
    "title": "Kabini Black Panther & Elephant River Safari",
    "desc": "Boat and jeep safaris along the Kabini backwaters searching for the mysterious black leopard.",
    "image": "/assets/images/destinations/nagarhole-kabini-reserve.jpg",
    "link": "/packages/nagarhole-kabini-reserve",
    "linkText": "Book Expedition",
    "location": "Nagarhole National Park (Kabini), India",
    "rating": 4.9,
    "reviews": 340,
    "offprice": "10% off",
    "price": "510",
    "duration": "4 Days – 3 Nights",
    "feature": "Rare Species",
    "slug": "nagarhole-kabini-reserve"
  },
  {
    "id": 39,
    "title": "Pench Mowgli Jungle & Teak Forest Trail",
    "desc": "Follow the original trails of Kipling's Mowgli across Turia and Touria zones with experienced wildlife biologists.",
    "image": "/assets/images/destinations/pench-tiger-reserve.jpg",
    "link": "/packages/pench-tiger-reserve",
    "linkText": "Book Expedition",
    "location": "Pench Tiger Reserve, India",
    "rating": 4.8,
    "reviews": 210,
    "offprice": null,
    "price": "440",
    "duration": "4 Days – 3 Nights",
    "feature": "Tiger Territory",
    "slug": "pench-tiger-reserve"
  },
  {
    "id": 40,
    "title": "Panna Tiger Gorges & Ken River Boat Safari",
    "desc": "Scenic canyon safaris combined with riverboat wildlife cruises searching for gharials and cliff-nesting vultures.",
    "image": "/assets/images/destinations/panna-national-park.jpg",
    "link": "/packages/panna-national-park",
    "linkText": "Book Expedition",
    "location": "Panna National Park, India",
    "rating": 4.7,
    "reviews": 175,
    "offprice": "10% off",
    "price": "420",
    "duration": "3 Days – 2 Nights",
    "feature": "Conservation Tour",
    "slug": "panna-national-park"
  },
  {
    "id": 41,
    "title": "Satpura Walking Safari & Denwa Canoe Trail",
    "desc": "Explore pristine sal forests on foot and paddle silent canoes to observe wildlife on tranquil backwaters.",
    "image": "/assets/images/destinations/satpura-tiger-reserve.jpg",
    "link": "/packages/satpura-tiger-reserve",
    "linkText": "Book Expedition",
    "location": "Satpura Tiger Reserve, India",
    "rating": 4.9,
    "reviews": 220,
    "offprice": "15% off",
    "price": "490",
    "duration": "4 Days – 3 Nights",
    "feature": "Walking Safari",
    "slug": "satpura-tiger-reserve"
  },
  {
    "id": 42,
    "title": "Dudhwa Terai Grasslands & Rhino Tracking",
    "desc": "Trek the untouched Terai forest corridors to witness rhino conservation and rare grassland birds.",
    "image": "/assets/images/destinations/dudhwa-national-park.jpg",
    "link": "/packages/dudhwa-national-park",
    "linkText": "Book Expedition",
    "location": "Dudhwa National Park, India",
    "rating": 4.7,
    "reviews": 145,
    "offprice": null,
    "price": "410",
    "duration": "3 Days – 2 Nights",
    "feature": "UNESCO Sanctuary",
    "slug": "dudhwa-national-park"
  },
  {
    "id": 43,
    "title": "Manas Transboundary Foothills & Golden Langur Quest",
    "desc": "River rafting along the Bhutan border and jeep safaris to find the rare Golden Langur and Pygmy Hog.",
    "image": "/assets/images/destinations/manas-national-park.jpg",
    "link": "/packages/manas-national-park",
    "linkText": "Book Expedition",
    "location": "Manas National Park, India",
    "rating": 4.8,
    "reviews": 160,
    "offprice": "10% off",
    "price": "430",
    "duration": "4 Days – 3 Nights",
    "feature": "UNESCO Reserve",
    "slug": "manas-national-park"
  },
  {
    "id": 44,
    "title": "Periyar Lake Boat & Bamboo Rafting Safari",
    "desc": "Full-day jungle hiking and bamboo rafting across the Periyar lake watching wild elephant herds.",
    "image": "/assets/images/destinations/periyar-national-park.jpg",
    "link": "/packages/periyar-national-park",
    "linkText": "Book Expedition",
    "location": "Periyar National Park, India",
    "rating": 4.7,
    "reviews": 190,
    "offprice": null,
    "price": "380",
    "duration": "3 Days – 2 Nights",
    "feature": "River Expedition",
    "slug": "periyar-national-park"
  },
  {
    "id": 45,
    "title": "Bandipur Nilgiri Foothills Tiger Safari",
    "desc": "Explore ancient sandalwood tracks and elephant corridors in open safari cruisers with state naturalists.",
    "image": "/assets/images/destinations/bandipur-national-park.jpg",
    "link": "/packages/bandipur-national-park",
    "linkText": "Book Expedition",
    "location": "Bandipur National Park, India",
    "rating": 4.8,
    "reviews": 210,
    "offprice": "10% off",
    "price": "420",
    "duration": "3 Days – 2 Nights",
    "feature": "Tiger Territory",
    "slug": "bandipur-national-park"
  },
  {
    "id": 46,
    "title": "Sundarbans Mangrove Delta & Boat Cruiser Safari",
    "desc": "Navigate silent tidal creeks on luxury motorized boats to glimpse swimming tigers and giant estuarine crocodiles.",
    "image": "/assets/images/destinations/sunderbans-mangrove-delta.jpg",
    "link": "/packages/sunderbans-mangrove-delta",
    "linkText": "Book Expedition",
    "location": "Sundarbans National Park, India",
    "rating": 4.7,
    "reviews": 190,
    "offprice": "10% off",
    "price": "390",
    "duration": "3 Days – 2 Nights",
    "feature": "UNESCO Reserve",
    "slug": "sunderbans-mangrove-delta"
  },
  {
    "id": 47,
    "title": "Bharatpur Avian Photography & Wetland Rickshaw Tour",
    "desc": "Cycle rickshaw photography tours guided by trained birders capturing nesting heronries and migratory waterbirds.",
    "image": "/assets/images/destinations/keoladeo-national-park.jpg",
    "link": "/packages/keoladeo-national-park",
    "linkText": "Book Expedition",
    "location": "Keoladeo Ghana National Park, India",
    "rating": 4.8,
    "reviews": 160,
    "offprice": null,
    "price": "290",
    "duration": "3 Days – 2 Nights",
    "feature": "Bird Sanctuary",
    "slug": "keoladeo-national-park"
  },
  {
    "id": 48,
    "title": "Silent Valley Lion-Tailed Macaque Rainforest Trek",
    "desc": "Eco-trekking deep into Kerala's protected primary canopy searching for rare endemic primates.",
    "image": "/assets/images/destinations/silent-valley-national-park.jpg",
    "link": "/packages/silent-valley-national-park",
    "linkText": "Book Expedition",
    "location": "Silent Valley National Park, India",
    "rating": 4.7,
    "reviews": 135,
    "offprice": "10% off",
    "price": "350",
    "duration": "3 Days – 2 Nights",
    "feature": "Rare Species",
    "slug": "silent-valley-national-park"
  },
  {
    "id": 49,
    "title": "Namdapha Four Big Cats & Clouded Leopard Trek",
    "desc": "Multi-day backcountry expedition into India's wildest primary jungle for rare cat telemetry and birding.",
    "image": "/assets/images/destinations/namdapha-national-park.jpg",
    "link": "/packages/namdapha-national-park",
    "linkText": "Book Expedition",
    "location": "Namdapha National Park, India",
    "rating": 4.9,
    "reviews": 110,
    "offprice": "15% off",
    "price": "680",
    "duration": "6 Days – 5 Nights",
    "feature": "Rare Species",
    "slug": "namdapha-national-park"
  },
  {
    "id": 50,
    "title": "Himalayan Alpine Wildlife & Tragopan Trek",
    "desc": "Scenic mountain eco-trek through pristine high-altitude valleys with village homestays and expert birders.",
    "image": "/assets/images/destinations/great-himalayan-national-park.jpg",
    "link": "/packages/great-himalayan-national-park",
    "linkText": "Book Expedition",
    "location": "Great Himalayan National Park, India",
    "rating": 4.8,
    "reviews": 125,
    "offprice": null,
    "price": "560",
    "duration": "5 Days – 4 Nights",
    "feature": "High Altitude Quest",
    "slug": "great-himalayan-national-park"
  },
  {
    "id": 51,
    "title": "Chitwan Jungle Safari & Rapti River Canoe Quest",
    "desc": "Open jeep safaris and silent dugout canoe rides spotting rhinos and sunbathing gharials along riverbanks.",
    "image": "/assets/images/destinations/chitwan-national-park-nepal.jpg",
    "link": "/packages/chitwan-national-park-nepal",
    "linkText": "Book Expedition",
    "location": "Chitwan National Park, Nepal",
    "rating": 4.7,
    "reviews": 190,
    "offprice": null,
    "price": "380",
    "duration": "3 Days – 2 Nights",
    "feature": "UNESCO Sanctuary",
    "slug": "chitwan-national-park-nepal"
  },
  {
    "id": 52,
    "title": "Bardia Walking Tiger Safari & Karnali River Cruise",
    "desc": "On-foot tiger tracking accompanied by veteran Nepali naturalists and drift-boating for river dolphins.",
    "image": "/assets/images/destinations/bardia-national-park.jpg",
    "link": "/packages/bardia-national-park",
    "linkText": "Book Expedition",
    "location": "Bardia National Park, Nepal",
    "rating": 4.9,
    "reviews": 175,
    "offprice": "10% off",
    "price": "420",
    "duration": "4 Days – 3 Nights",
    "feature": "Tiger Territory",
    "slug": "bardia-national-park"
  },
  {
    "id": 53,
    "title": "Mudumalai Forest Corridor & Elephant Trail",
    "desc": "Open-top vehicle drives through Moyar Gorge tracking tiger pugmarks and foraging elephant families.",
    "image": "/assets/images/destinations/mudumalai-national-park.jpg",
    "link": "/packages/mudumalai-national-park",
    "linkText": "Book Expedition",
    "location": "Mudumalai National Park, India",
    "rating": 4.7,
    "reviews": 180,
    "offprice": null,
    "price": "390",
    "duration": "3 Days – 2 Nights",
    "feature": "Elephant Haven",
    "slug": "mudumalai-national-park"
  },
  {
    "id": 54,
    "title": "Topslip Anamalai Rainforest & Wildlife Trek",
    "desc": "Guided nature walks through evergreen rainforest canopies spotting Malabar hornbills and primates.",
    "image": "/assets/images/destinations/anamalai-tiger-reserve.jpg",
    "link": "/packages/anamalai-tiger-reserve",
    "linkText": "Book Expedition",
    "location": "Anamalai Tiger Reserve (Topslip), India",
    "rating": 4.7,
    "reviews": 140,
    "offprice": "10% off",
    "price": "370",
    "duration": "3 Days – 2 Nights",
    "feature": "Rare Species",
    "slug": "anamalai-tiger-reserve"
  },
  {
    "id": 55,
    "title": "Munnar Shola Grasslands & Nilgiri Tahr Quest",
    "desc": "Highland walking safari to the base of Anamudi peak observing wild mountain goats up close.",
    "image": "/assets/images/destinations/eravikulam-national-park.jpg",
    "link": "/packages/eravikulam-national-park",
    "linkText": "Book Expedition",
    "location": "Eravikulam National Park, India",
    "rating": 4.7,
    "reviews": 165,
    "offprice": null,
    "price": "310",
    "duration": "2 Days – 1 Night",
    "feature": "High Altitude Quest",
    "slug": "eravikulam-national-park"
  },
  {
    "id": 56,
    "title": "Yala Block 1 Leopard Tracking & Coastal Safari",
    "desc": "Custom open 4x4 cruiser safaris exploring prime leopard rocks and coastal lagoons in Block 1 and 2.",
    "image": "/assets/images/destinations/yala-national-park.jpg",
    "link": "/packages/yala-national-park",
    "linkText": "Book Expedition",
    "location": "Yala National Park, Sri Lanka",
    "rating": 4.8,
    "reviews": 290,
    "offprice": "15% off",
    "price": "380",
    "duration": "4 Days – 3 Nights",
    "feature": "Leopard Territory",
    "slug": "yala-national-park"
  },
  {
    "id": 57,
    "title": "Wilpattu Natural Willus & Sloth Bear Trail",
    "desc": "Quiet, uncrowded safaris around pristine sand-rimmed lakes encountering leopards and foraging sloth bears.",
    "image": "/assets/images/destinations/wilpattu-national-park.jpg",
    "link": "/packages/wilpattu-national-park",
    "linkText": "Book Expedition",
    "location": "Wilpattu National Park, Sri Lanka",
    "rating": 4.8,
    "reviews": 210,
    "offprice": "10% off",
    "price": "390",
    "duration": "4 Days – 3 Nights",
    "feature": "Offbeat Safari",
    "slug": "wilpattu-national-park"
  },
  {
    "id": 58,
    "title": "Udawalawe Elephant Sanctuary & Grassland Safari",
    "desc": "Guaranteed encounters with massive elephant herds and visit the famous baby elephant rehabilitation center.",
    "image": "/assets/images/destinations/udawalawe-national-park.jpg",
    "link": "/packages/udawalawe-national-park",
    "linkText": "Book Expedition",
    "location": "Udawalawe National Park, Sri Lanka",
    "rating": 4.7,
    "reviews": 180,
    "offprice": null,
    "price": "340",
    "duration": "3 Days – 2 Nights",
    "feature": "Family Friendly",
    "slug": "udawalawe-national-park"
  },
  {
    "id": 59,
    "title": "Minneriya 'The Great Gathering' Elephant Spectacle",
    "desc": "Witness up to 300 Asian elephants in a single panoramic vista feeding on ancient lakebed pastures.",
    "image": "/assets/images/destinations/minneriya-national-park.jpg",
    "link": "/packages/minneriya-national-park",
    "linkText": "Book Expedition",
    "location": "Minneriya National Park, Sri Lanka",
    "rating": 4.9,
    "reviews": 260,
    "offprice": "10% off",
    "price": "360",
    "duration": "3 Days – 2 Nights",
    "feature": "Wildlife Spectacle",
    "slug": "minneriya-national-park"
  },
  {
    "id": 60,
    "title": "Sinharaja Virgin Rainforest Endemic Birding Trek",
    "desc": "Guided on-foot botanist treks through pristine virgin canopy to view mixed-species bird feeding waves.",
    "image": "/assets/images/destinations/sinharaja-forest-reserve.jpg",
    "link": "/packages/sinharaja-forest-reserve",
    "linkText": "Book Expedition",
    "location": "Sinharaja Forest Reserve, Sri Lanka",
    "rating": 4.8,
    "reviews": 150,
    "offprice": null,
    "price": "320",
    "duration": "3 Days – 2 Nights",
    "feature": "Bird Sanctuary",
    "slug": "sinharaja-forest-reserve"
  },
  {
    "id": 61,
    "title": "Bundala Coastal Lagoon & Flamingo Photography Tour",
    "desc": "Jeep safaris around coastal sand dunes and salt pans capturing vast flocks of migratory waterbirds.",
    "image": "/assets/images/destinations/bundala-national-park.jpg",
    "link": "/packages/bundala-national-park",
    "linkText": "Book Expedition",
    "location": "Bundala National Park, Sri Lanka",
    "rating": 4.7,
    "reviews": 130,
    "offprice": null,
    "price": "310",
    "duration": "2 Days – 1 Night",
    "feature": "Bird Sanctuary",
    "slug": "bundala-national-park"
  },
  {
    "id": 62,
    "title": "Kumana Mangrove Heronry & Leopard Quest",
    "desc": "Secluded game drives along the wild eastern coast observing rare breeding waterbirds and predators.",
    "image": "/assets/images/destinations/kumana-national-park.jpg",
    "link": "/packages/kumana-national-park",
    "linkText": "Book Expedition",
    "location": "Kumana National Park, Sri Lanka",
    "rating": 4.7,
    "reviews": 120,
    "offprice": "10% off",
    "price": "330",
    "duration": "3 Days – 2 Nights",
    "feature": "Bird Sanctuary",
    "slug": "kumana-national-park"
  },
  {
    "id": 63,
    "title": "Wasgamuwa Untamed Elephant & Sloth Bear Safari",
    "desc": "Discover untouched riverine forests along the Mahaweli River with very low tourist traffic.",
    "image": "/assets/images/destinations/wasgamuwa-national-park.jpg",
    "link": "/packages/wasgamuwa-national-park",
    "linkText": "Book Expedition",
    "location": "Wasgamuwa National Park, Sri Lanka",
    "rating": 4.7,
    "reviews": 115,
    "offprice": null,
    "price": "340",
    "duration": "3 Days – 2 Nights",
    "feature": "Offbeat Safari",
    "slug": "wasgamuwa-national-park"
  },
  {
    "id": 64,
    "title": "Horton Plains World's End & Cloud Forest Walk",
    "desc": "Sunrise hike across rolling highland plains to view the 880m sheer drop at World's End.",
    "image": "/assets/images/destinations/horton-plains-national-park.jpg",
    "link": "/packages/horton-plains-national-park",
    "linkText": "Book Expedition",
    "location": "Horton Plains National Park, Sri Lanka",
    "rating": 4.8,
    "reviews": 190,
    "offprice": null,
    "price": "280",
    "duration": "2 Days – 1 Night",
    "feature": "Walking Safari",
    "slug": "horton-plains-national-park"
  },
  {
    "id": 65,
    "title": "Pigeon Island Coral Reef & Reef Shark Snorkel",
    "desc": "Speedboat excursion to Pigeon Island for guided marine snorkeling with docile reef sharks and sea turtles.",
    "image": "/assets/images/destinations/pigeon-island-national-park.jpg",
    "link": "/packages/pigeon-island-national-park",
    "linkText": "Book Expedition",
    "location": "Pigeon Island National Park, Sri Lanka",
    "rating": 4.8,
    "reviews": 210,
    "offprice": "10% off",
    "price": "260",
    "duration": "2 Days – 1 Night",
    "feature": "Marine Wonder",
    "slug": "pigeon-island-national-park"
  },
  {
    "id": 66,
    "title": "Pantanal Jaguar River Boat Expedition",
    "desc": "Private motorboats equipped with swivel seats tracking wild jaguars stalking caiman along riverbanks.",
    "image": "/assets/images/destinations/pantanal-wetlands-brazil.jpg",
    "link": "/packages/pantanal-wetlands-brazil",
    "linkText": "Book Expedition",
    "location": "Pantanal Matogrossense National Park, Brazil",
    "rating": 5,
    "reviews": 310,
    "offprice": "15% off",
    "price": "850",
    "duration": "6 Days – 5 Nights",
    "feature": "Jaguar Trail",
    "slug": "pantanal-wetlands-brazil"
  },
  {
    "id": 67,
    "title": "Deep Amazon Clay Lick & Canopy Walkway Odyssey",
    "desc": "Dawn boat visits to famous Chuncho macaw clay licks and night searches for black caimans and tree frogs.",
    "image": "/assets/images/destinations/amazon-rainforest-peru-ecuador.jpg",
    "link": "/packages/amazon-rainforest-peru-ecuador",
    "linkText": "Book Expedition",
    "location": "Amazon Rainforest (Yasuni & Tambopata), Peru / Ecuador",
    "rating": 4.9,
    "reviews": 270,
    "offprice": "10% off",
    "price": "680",
    "duration": "5 Days – 4 Nights",
    "feature": "Rainforest Expedition",
    "slug": "amazon-rainforest-peru-ecuador"
  },
  {
    "id": 68,
    "title": "Tortuguero Canal Boat & Sea Turtle Nesting Vigil",
    "desc": "Electric canal boat tours through lush jungle canals and nighttime guided sea turtle nesting observations.",
    "image": "/assets/images/destinations/tortuguero-national-park.jpg",
    "link": "/packages/tortuguero-national-park",
    "linkText": "Book Expedition",
    "location": "Tortuguero National Park, Costa Rica",
    "rating": 4.8,
    "reviews": 210,
    "offprice": null,
    "price": "520",
    "duration": "3 Days – 2 Nights",
    "feature": "Marine Wonder",
    "slug": "tortuguero-national-park"
  },
  {
    "id": 69,
    "title": "Corcovado Sirena Station Deep Jungle Trek",
    "desc": "Fly into Sirena Ranger Station for backcountry tracking of Baird's tapirs, pumas, and all four Costa Rican monkey species.",
    "image": "/assets/images/destinations/corcovado-national-park.jpg",
    "link": "/packages/corcovado-national-park",
    "linkText": "Book Expedition",
    "location": "Corcovado National Park, Costa Rica",
    "rating": 4.9,
    "reviews": 230,
    "offprice": "15% off",
    "price": "580",
    "duration": "4 Days – 3 Nights",
    "feature": "Rainforest Expedition",
    "slug": "corcovado-national-park"
  },
  {
    "id": 70,
    "title": "Bwindi Mountain Gorilla Habituation Trek",
    "desc": "Exclusive 4-hour immersion with a habituated gorilla family guided by Uganda Wildlife Authority primatologists.",
    "image": "/assets/images/destinations/bwindi-gorilla-reserve.jpg",
    "link": "/packages/bwindi-gorilla-reserve",
    "linkText": "Book Expedition",
    "location": "Bwindi Impenetrable National Park, Uganda",
    "rating": 5,
    "reviews": 340,
    "offprice": "10% off",
    "price": "890",
    "duration": "4 Days – 3 Nights",
    "feature": "Gorilla Tracking",
    "slug": "bwindi-gorilla-reserve"
  },
  {
    "id": 71,
    "title": "Borneo Klotok Riverboat & Orangutan Camp Leakey",
    "desc": "Live aboard a traditional wooden klotok boat traveling upriver to Dr. Birute Galdikas' Camp Leakey feeding platforms.",
    "image": "/assets/images/destinations/tanjung-puting-borneo.jpg",
    "link": "/packages/tanjung-puting-borneo",
    "linkText": "Book Expedition",
    "location": "Tanjung Puting National Park (Borneo), Indonesia",
    "rating": 4.9,
    "reviews": 280,
    "offprice": "10% off",
    "price": "560",
    "duration": "4 Days – 3 Nights",
    "feature": "Rainforest Expedition",
    "slug": "tanjung-puting-borneo"
  },
  {
    "id": 72,
    "title": "Sumatra Jungle Trekking & Orangutan River Safari",
    "desc": "Multi-day trekking in primary rainforest followed by thrilling traditional river tubing down the Bohorok River.",
    "image": "/assets/images/destinations/gunung-leuser-sumatra.jpg",
    "link": "/packages/gunung-leuser-sumatra",
    "linkText": "Book Expedition",
    "location": "Gunung Leuser National Park, Indonesia",
    "rating": 4.8,
    "reviews": 210,
    "offprice": "15% off",
    "price": "460",
    "duration": "4 Days – 3 Nights",
    "feature": "Rainforest Expedition",
    "slug": "gunung-leuser-sumatra"
  },
  {
    "id": 73,
    "title": "Danum Valley Ancient Rainforest & Pygmy Elephant Quest",
    "desc": "Canopy walkway birding and night 4x4 open safaris in search of elusive Bornean clouded leopards.",
    "image": "/assets/images/destinations/danum-valley-borneo.jpg",
    "link": "/packages/danum-valley-borneo",
    "linkText": "Book Expedition",
    "location": "Danum Valley Conservation Area, Malaysia",
    "rating": 4.9,
    "reviews": 195,
    "offprice": null,
    "price": "690",
    "duration": "4 Days – 3 Nights",
    "feature": "Rainforest Expedition",
    "slug": "danum-valley-borneo"
  },
  {
    "id": 74,
    "title": "Kinabatangan River Boat Safaris & Oxbow Lakes",
    "desc": "Dawn and dusk electric boat cruises through oxbow lakes watching wild elephant herds bathe.",
    "image": "/assets/images/destinations/kinabatangan-river-reserve.jpg",
    "link": "/packages/kinabatangan-river-reserve",
    "linkText": "Book Expedition",
    "location": "Kinabatangan River Reserve, Malaysia",
    "rating": 4.8,
    "reviews": 230,
    "offprice": "10% off",
    "price": "480",
    "duration": "3 Days – 2 Nights",
    "feature": "River Expedition",
    "slug": "kinabatangan-river-reserve"
  },
  {
    "id": 75,
    "title": "Daintree Rainforest Ancient Canopy & Crocodile Cruise",
    "desc": "Guided Aboriginal Kuku Yalanji cultural walk and boat cruise tracking giant estuarine crocodiles.",
    "image": "/assets/images/destinations/daintree-rainforest.jpg",
    "link": "/packages/daintree-rainforest",
    "linkText": "Book Expedition",
    "location": "Daintree Rainforest, Australia",
    "rating": 4.8,
    "reviews": 210,
    "offprice": null,
    "price": "510",
    "duration": "3 Days – 2 Nights",
    "feature": "UNESCO Reserve",
    "slug": "daintree-rainforest"
  },
  {
    "id": 76,
    "title": "Kakadu Yellow Water Billabong & Rock Art Safari",
    "desc": "Dawn billabong boat cruise surrounded by hunting saltwater crocodiles and visit 20,000-year-old rock art galleries.",
    "image": "/assets/images/destinations/kakadu-national-park.jpg",
    "link": "/packages/kakadu-national-park",
    "linkText": "Book Expedition",
    "location": "Kakadu National Park, Australia",
    "rating": 4.8,
    "reviews": 190,
    "offprice": null,
    "price": "530",
    "duration": "4 Days – 3 Nights",
    "feature": "UNESCO Reserve",
    "slug": "kakadu-national-park"
  },
  {
    "id": 77,
    "title": "Manu Untamed Cloud Forest to Lowland Amazon Trail",
    "desc": "Deep expedition boat voyage through protected biological stations with researcher naturalists.",
    "image": "/assets/images/destinations/manu-national-park.jpg",
    "link": "/packages/manu-national-park",
    "linkText": "Book Expedition",
    "location": "Manu National Park, Peru",
    "rating": 4.9,
    "reviews": 180,
    "offprice": "15% off",
    "price": "790",
    "duration": "6 Days – 5 Nights",
    "feature": "Rainforest Expedition",
    "slug": "manu-national-park"
  },
  {
    "id": 78,
    "title": "Murchison Falls Victoria Nile & Shoebill Expedition",
    "desc": "Navigate the Victoria Nile delta to spot prehistoric Shoebill storks and hike to the apex of the thunderous falls.",
    "image": "/assets/images/destinations/murchison-falls-reserve.jpg",
    "link": "/packages/murchison-falls-reserve",
    "linkText": "Book Expedition",
    "location": "Murchison Falls National Park, Uganda",
    "rating": 4.8,
    "reviews": 165,
    "offprice": null,
    "price": "590",
    "duration": "4 Days – 3 Nights",
    "feature": "River Expedition",
    "slug": "murchison-falls-reserve"
  },
  {
    "id": 79,
    "title": "Everglades Mangrove Kayak & Airboat Eco-Tour",
    "desc": "Paddle through Ten Thousand Islands mangrove tunnels and take guided biologist airboat safaris.",
    "image": "/assets/images/destinations/everglades-national-park.jpg",
    "link": "/packages/everglades-national-park",
    "linkText": "Book Expedition",
    "location": "Everglades National Park, USA",
    "rating": 4.7,
    "reviews": 190,
    "offprice": null,
    "price": "340",
    "duration": "3 Days – 2 Nights",
    "feature": "Family Friendly",
    "slug": "everglades-national-park"
  },
  {
    "id": 80,
    "title": "Monteverde Hanging Bridges & Quetzal Birding Quest",
    "desc": "Walk suspended canopy bridges through swirling clouds spotting the mythical iridescent Quetzal.",
    "image": "/assets/images/destinations/monteverde-cloud-forest.jpg",
    "link": "/packages/monteverde-cloud-forest",
    "linkText": "Book Expedition",
    "location": "Monteverde Cloud Forest Reserve, Costa Rica",
    "rating": 4.8,
    "reviews": 220,
    "offprice": "10% off",
    "price": "390",
    "duration": "3 Days – 2 Nights",
    "feature": "Bird Sanctuary",
    "slug": "monteverde-cloud-forest"
  },
  {
    "id": 81,
    "title": "Svalbard Arctic Pack Ice & Polar Bear Cruise",
    "desc": "Expedition vessel voyage through frozen fjords and pack ice edges in search of hunting polar bears and massive walrus haulouts.",
    "image": "/assets/images/destinations/svalbard-polar-bear-arctic.jpg",
    "link": "/packages/svalbard-polar-bear-arctic",
    "linkText": "Book Expedition",
    "location": "Svalbard Archipelago & Spitsbergen, Norway",
    "rating": 5,
    "reviews": 280,
    "offprice": "10% off",
    "price": "1250",
    "duration": "8 Days – 7 Nights",
    "feature": "Polar & Arctic",
    "slug": "svalbard-polar-bear-arctic"
  },
  {
    "id": 82,
    "title": "Churchill Tundra Buggy & Autumn Polar Bear Quest",
    "desc": "Ride massive custom tundra rovers across the subarctic tundra for up-close encounters with sparring polar bears.",
    "image": "/assets/images/destinations/churchill-polar-bear-capital.jpg",
    "link": "/packages/churchill-polar-bear-capital",
    "linkText": "Book Expedition",
    "location": "Churchill Polar Bear Capital, Canada",
    "rating": 4.9,
    "reviews": 220,
    "offprice": null,
    "price": "980",
    "duration": "5 Days – 4 Nights",
    "feature": "Polar & Arctic",
    "slug": "churchill-polar-bear-capital"
  },
  {
    "id": 83,
    "title": "Katmai Brooks Falls Brown Bear & Salmon Run",
    "desc": "Fly-in floatplane expedition to elevated platforms watching giant grizzly bears catch leaping salmon mid-air.",
    "image": "/assets/images/destinations/katmai-brown-bear-reserve.jpg",
    "link": "/packages/katmai-brown-bear-reserve",
    "linkText": "Book Expedition",
    "location": "Katmai National Park & Brooks Falls, USA",
    "rating": 4.9,
    "reviews": 260,
    "offprice": "15% off",
    "price": "870",
    "duration": "4 Days – 3 Nights",
    "feature": "Photography Escort",
    "slug": "katmai-brown-bear-reserve"
  },
  {
    "id": 84,
    "title": "Denali Wilderness Taiga & Tundra Wildlife Safari",
    "desc": "Travel deep into the park interior on official transit buses spotting the 'Big Five of the North'.",
    "image": "/assets/images/destinations/denali-national-park-alaska.jpg",
    "link": "/packages/denali-national-park-alaska",
    "linkText": "Book Expedition",
    "location": "Denali National Park & Preserve, USA",
    "rating": 4.8,
    "reviews": 240,
    "offprice": "10% off",
    "price": "620",
    "duration": "5 Days – 4 Nights",
    "feature": "Polar & Arctic",
    "slug": "denali-national-park-alaska"
  },
  {
    "id": 85,
    "title": "Yellowstone Lamar Valley Wolf Tracking & Geyser Safari",
    "desc": "Dawn spotting scope tracking of the famous Junction Butte wolf pack in Lamar Valley and geyser basin explorations.",
    "image": "/assets/images/destinations/yellowstone-national-park.jpg",
    "link": "/packages/yellowstone-national-park",
    "linkText": "Book Expedition",
    "location": "Yellowstone National Park, USA",
    "rating": 4.8,
    "reviews": 340,
    "offprice": "10% off",
    "price": "620",
    "duration": "5 Days – 4 Nights",
    "feature": "Big Five",
    "slug": "yellowstone-national-park"
  },
  {
    "id": 86,
    "title": "Wrangell-St. Elias Root Glacier & Fly-In Backcountry",
    "desc": "Bush plane flightseeing and glacier crampon hikes exploring ice caves and spotting Dall sheep.",
    "image": "/assets/images/destinations/wrangell-st-elias-park.jpg",
    "link": "/packages/wrangell-st-elias-park",
    "linkText": "Book Expedition",
    "location": "Wrangell-St. Elias National Park, USA",
    "rating": 4.8,
    "reviews": 140,
    "offprice": null,
    "price": "750",
    "duration": "4 Days – 3 Nights",
    "feature": "High Altitude Quest",
    "slug": "wrangell-st-elias-park"
  },
  {
    "id": 87,
    "title": "Vancouver Island Whale Watching & Coastal Bear Boat Safari",
    "desc": "Zodiac boat safaris through Clayoquot Sound observing feeding gray whales and shore bears turning beach rocks.",
    "image": "/assets/images/destinations/pacific-rim-national-park.jpg",
    "link": "/packages/pacific-rim-national-park",
    "linkText": "Book Expedition",
    "location": "Pacific Rim National Park Reserve, Canada",
    "rating": 4.9,
    "reviews": 230,
    "offprice": "10% off",
    "price": "580",
    "duration": "4 Days – 3 Nights",
    "feature": "Marine Wonder",
    "slug": "pacific-rim-national-park"
  },
  {
    "id": 88,
    "title": "Kenai Fjords Glacier Cruise & Orca Pod Expedition",
    "desc": "Catamaran wildlife cruise into Resurrection Bay viewing calving tidewater glaciers and hunting killer whales.",
    "image": "/assets/images/destinations/kenai-fjords-national-park.jpg",
    "link": "/packages/kenai-fjords-national-park",
    "linkText": "Book Expedition",
    "location": "Kenai Fjords National Park, USA",
    "rating": 4.9,
    "reviews": 260,
    "offprice": "15% off",
    "price": "640",
    "duration": "3 Days – 2 Nights",
    "feature": "Marine Wonder",
    "slug": "kenai-fjords-national-park"
  },
  {
    "id": 89,
    "title": "South Georgia King Penguin & Antarctic Ice Odyssey",
    "desc": "Expedition ship cruise landing Zodiacs on beaches filled with 300,000 king penguins and giant elephant seals.",
    "image": "/assets/images/destinations/south-georgia-antarctica.jpg",
    "link": "/packages/south-georgia-antarctica",
    "linkText": "Book Expedition",
    "location": "South Georgia & Antarctic Peninsula, Antarctica / UK Territory",
    "rating": 5,
    "reviews": 310,
    "offprice": "10% off",
    "price": "1850",
    "duration": "12 Days – 11 Nights",
    "feature": "Polar & Arctic",
    "slug": "south-georgia-antarctica"
  },
  {
    "id": 90,
    "title": "High Arctic Ellesmere Muskox & White Wolf Expedition",
    "desc": "Fly-in tundra base camp trekking under 24-hour midnight sun to encounter ancient muskoxen herds.",
    "image": "/assets/images/destinations/ellesmere-island-arctic.jpg",
    "link": "/packages/ellesmere-island-arctic",
    "linkText": "Book Expedition",
    "location": "Ellesmere Island Arctic Reserve (Quttinirpaaq), Canada",
    "rating": 4.9,
    "reviews": 110,
    "offprice": null,
    "price": "1450",
    "duration": "7 Days – 6 Nights",
    "feature": "Polar & Arctic",
    "slug": "ellesmere-island-arctic"
  },
  {
    "id": 91,
    "title": "Galapagos First-Class Catamaran Wildlife Cruise",
    "desc": "Luxury expedition vessel hopping between remote islands to snorkel with penguins, sea lions, and marine iguanas.",
    "image": "/assets/images/destinations/galapagos-islands.jpg",
    "link": "/packages/galapagos-islands",
    "linkText": "Book Expedition",
    "location": "Galapagos Islands National Park, Ecuador",
    "rating": 5,
    "reviews": 410,
    "offprice": "10% off",
    "price": "1100",
    "duration": "7 Days – 6 Nights",
    "feature": "Marine Wonder",
    "slug": "galapagos-islands"
  },
  {
    "id": 92,
    "title": "Outer Great Barrier Reef Luxury Catamaran Safari",
    "desc": "Cruise to untouched outer coral reefs for guided marine biologist snorkeling and scuba diving expeditions.",
    "image": "/assets/images/destinations/great-barrier-reef-reserve.jpg",
    "link": "/packages/great-barrier-reef-reserve",
    "linkText": "Book Expedition",
    "location": "Great Barrier Reef Marine Park, Australia",
    "rating": 4.9,
    "reviews": 350,
    "offprice": "15% off",
    "price": "650",
    "duration": "4 Days – 3 Nights",
    "feature": "Marine Wonder",
    "slug": "great-barrier-reef-reserve"
  },
  {
    "id": 93,
    "title": "Ningaloo Reef Whale Shark & Manta Ray Swim",
    "desc": "Spotter-plane guided swimming encounters alongside massive gentle whale sharks and outer reef snorkeling.",
    "image": "/assets/images/destinations/ningaloo-marine-park.jpg",
    "link": "/packages/ningaloo-marine-park",
    "linkText": "Book Expedition",
    "location": "Ningaloo Marine Park, Australia",
    "rating": 5,
    "reviews": 290,
    "offprice": "10% off",
    "price": "710",
    "duration": "4 Days – 3 Nights",
    "feature": "Marine Wonder",
    "slug": "ningaloo-marine-park"
  },
  {
    "id": 94,
    "title": "Komodo Dragon Island Trek & Manta Point Snorkel",
    "desc": "Liveaboard wooden schooner cruise trekking Rinca island dragons and swimming with giant pelagic manta rays.",
    "image": "/assets/images/destinations/komodo-national-park.jpg",
    "link": "/packages/komodo-national-park",
    "linkText": "Book Expedition",
    "location": "Komodo National Park, Indonesia",
    "rating": 4.9,
    "reviews": 310,
    "offprice": "15% off",
    "price": "580",
    "duration": "4 Days – 3 Nights",
    "feature": "Marine Wonder",
    "slug": "komodo-national-park"
  },
  {
    "id": 95,
    "title": "Raja Ampat Karst Archipelago Diving & Snorkel Liveaboard",
    "desc": "Sail the four kings islands on a luxury phinisi schooner exploring Cape Kri, Manta Sandy, and Wayag lagoons.",
    "image": "/assets/images/destinations/raja-ampat-marine-park.jpg",
    "link": "/packages/raja-ampat-marine-park",
    "linkText": "Book Expedition",
    "location": "Raja Ampat Marine Park, Indonesia",
    "rating": 5,
    "reviews": 320,
    "offprice": "15% off",
    "price": "990",
    "duration": "7 Days – 6 Nights",
    "feature": "Marine Wonder",
    "slug": "raja-ampat-marine-park"
  },
  {
    "id": 96,
    "title": "Kaikoura Sperm Whale Watch & Dusky Dolphin Swim",
    "desc": "Hydrophone-guided catamaran cruise to observe diving sperm whales against the backdrop of snowy Kaikoura mountain ranges.",
    "image": "/assets/images/destinations/kaikoura-whale-sanctuary-nz.jpg",
    "link": "/packages/kaikoura-whale-sanctuary-nz",
    "linkText": "Book Expedition",
    "location": "Kaikoura Marine Sanctuary, New Zealand",
    "rating": 4.9,
    "reviews": 240,
    "offprice": "10% off",
    "price": "470",
    "duration": "3 Days – 2 Nights",
    "feature": "Marine Wonder",
    "slug": "kaikoura-whale-sanctuary-nz"
  },
  {
    "id": 97,
    "title": "Madagascar Indri Lemur & Chameleon Rainforest Trek",
    "desc": "Guided day and night forest walks to listen to morning Indri calls and discover bizarre endemic chameleons.",
    "image": "/assets/images/destinations/andasibe-mantadia-madagascar.jpg",
    "link": "/packages/andasibe-mantadia-madagascar",
    "linkText": "Book Expedition",
    "location": "Andasibe-Mantadia National Park, Madagascar",
    "rating": 4.8,
    "reviews": 210,
    "offprice": "15% off",
    "price": "540",
    "duration": "4 Days – 3 Nights",
    "feature": "Rare Species",
    "slug": "andasibe-mantadia-madagascar"
  },
  {
    "id": 98,
    "title": "Kangaroo Island Koala & Sea Lion Coastal Safari",
    "desc": "Walk among wild sea lions on the beach at Seal Bay and visit protected koala sanctuaries.",
    "image": "/assets/images/destinations/kangaroo-island-wildlife-sanctuary.jpg",
    "link": "/packages/kangaroo-island-wildlife-sanctuary",
    "linkText": "Book Expedition",
    "location": "Kangaroo Island Wildlife Sanctuary, Australia",
    "rating": 4.8,
    "reviews": 195,
    "offprice": null,
    "price": "480",
    "duration": "3 Days – 2 Nights",
    "feature": "Family Friendly",
    "slug": "kangaroo-island-wildlife-sanctuary"
  },
  {
    "id": 99,
    "title": "Monterey Bay Blue Whale & Sea Otter Marine Safari",
    "desc": "Marine biologist-led boat cruise through submarine canyon waters observing breaching humpbacks and giant blue whales.",
    "image": "/assets/images/destinations/monterey-bay-marine-sanctuary.jpg",
    "link": "/packages/monterey-bay-marine-sanctuary",
    "linkText": "Book Expedition",
    "location": "Monterey Bay National Marine Sanctuary, USA",
    "rating": 4.8,
    "reviews": 220,
    "offprice": "10% off",
    "price": "390",
    "duration": "3 Days – 2 Nights",
    "feature": "Marine Wonder",
    "slug": "monterey-bay-marine-sanctuary"
  },
  {
    "id": 100,
    "title": "Shark Bay Dugong Cruise & Monkey Mia Dolphin Experience",
    "desc": "Meet wild dolphins in knee-deep water and take sailing catamarans searching for elusive dugongs.",
    "image": "/assets/images/destinations/shark-bay-world-heritage.jpg",
    "link": "/packages/shark-bay-world-heritage",
    "linkText": "Book Expedition",
    "location": "Shark Bay World Heritage Area, Australia",
    "rating": 4.8,
    "reviews": 180,
    "offprice": null,
    "price": "460",
    "duration": "3 Days – 2 Nights",
    "feature": "Marine Wonder",
    "slug": "shark-bay-world-heritage"
  },
  {
    "id": 101,
    "title": "Himalayan Snow Leopard Winter Telemetry Expedition",
    "desc": "High-altitude spotting scopes and heated base camps in Rumbak Valley to track wild snow leopards.",
    "image": "/assets/images/destinations/hemis-national-park.jpg",
    "link": "/packages/hemis-national-park",
    "linkText": "Book Expedition",
    "location": "Hemis National Park, India",
    "rating": 4.9,
    "reviews": 210,
    "offprice": "20% off",
    "price": "750",
    "duration": "7 Days – 6 Nights",
    "feature": "High Altitude Quest",
    "slug": "hemis-national-park"
  },
  {
    "id": 102,
    "title": "Rwanda Virunga Gorillas & Golden Monkeys Quest",
    "desc": "Luxury trek through bamboo slopes to observe silverback gorilla groups and hyper-active golden monkey troops.",
    "image": "/assets/images/destinations/volcanoes-national-park-rwanda.jpg",
    "link": "/packages/volcanoes-national-park-rwanda",
    "linkText": "Book Expedition",
    "location": "Volcanoes National Park, Rwanda",
    "rating": 5,
    "reviews": 290,
    "offprice": null,
    "price": "950",
    "duration": "4 Days – 3 Nights",
    "feature": "Gorilla Tracking",
    "slug": "volcanoes-national-park-rwanda"
  },
  {
    "id": 103,
    "title": "Patagonia Puma Tracking & Glacier Horns Quest",
    "desc": "Private tracker vehicle following puma territories against the backdrop of Torres del Paine's granite peaks.",
    "image": "/assets/images/destinations/torres-del-paine-patagonia.jpg",
    "link": "/packages/torres-del-paine-patagonia",
    "linkText": "Book Expedition",
    "location": "Torres del Paine National Park, Chile",
    "rating": 4.9,
    "reviews": 240,
    "offprice": "15% off",
    "price": "890",
    "duration": "6 Days – 5 Nights",
    "feature": "High Altitude Quest",
    "slug": "torres-del-paine-patagonia"
  },
  {
    "id": 104,
    "title": "Canadian Rockies Wildlife & Icefields Parkway Tour",
    "desc": "Scenic wildlife tracking across Lake Louise, Moraine Lake, and Jasper's Maligne Valley for bears and elk.",
    "image": "/assets/images/destinations/banff-jasper-rockies.jpg",
    "link": "/packages/banff-jasper-rockies",
    "linkText": "Book Expedition",
    "location": "Banff & Jasper National Parks, Canada",
    "rating": 4.8,
    "reviews": 290,
    "offprice": null,
    "price": "590",
    "duration": "5 Days – 4 Nights",
    "feature": "Family Friendly",
    "slug": "banff-jasper-rockies"
  },
  {
    "id": 105,
    "title": "Simien Mountains Gelada Baboon & Highland Trek",
    "desc": "Walk peacefully within wild troops of hundreds of friendly Gelada baboons across sweeping alpine vistas.",
    "image": "/assets/images/destinations/simien-mountains-ethiopia.jpg",
    "link": "/packages/simien-mountains-ethiopia",
    "linkText": "Book Expedition",
    "location": "Simien Mountains National Park, Ethiopia",
    "rating": 4.8,
    "reviews": 170,
    "offprice": null,
    "price": "620",
    "duration": "5 Days – 4 Nights",
    "feature": "High Altitude Quest",
    "slug": "simien-mountains-ethiopia"
  },
  {
    "id": 106,
    "title": "Bale Mountains Ethiopian Wolf & Sanetti Plateau Quest",
    "desc": "High altitude 4x4 safaris across the afro-alpine plateau tracking the red Ethiopian wolf hunting giant mole rats.",
    "image": "/assets/images/destinations/bale-mountains-ethiopia.jpg",
    "link": "/packages/bale-mountains-ethiopia",
    "linkText": "Book Expedition",
    "location": "Bale Mountains National Park, Ethiopia",
    "rating": 4.8,
    "reviews": 135,
    "offprice": "10% off",
    "price": "640",
    "duration": "4 Days – 3 Nights",
    "feature": "Rare Species",
    "slug": "bale-mountains-ethiopia"
  },
  {
    "id": 107,
    "title": "Perito Moreno Ice Trek & Fitz Roy Wildlife Circuit",
    "desc": "Walk on the Perito Moreno glacier with crampons and hike beneath Mount Fitz Roy looking for condors.",
    "image": "/assets/images/destinations/los-glaciares-fitz-roy.jpg",
    "link": "/packages/los-glaciares-fitz-roy",
    "linkText": "Book Expedition",
    "location": "Los Glaciares National Park (Fitz Roy), Argentina",
    "rating": 4.9,
    "reviews": 250,
    "offprice": "15% off",
    "price": "720",
    "duration": "5 Days – 4 Nights",
    "feature": "High Altitude Quest",
    "slug": "los-glaciares-fitz-roy"
  },
  {
    "id": 108,
    "title": "Milford Sound Fiord Cruise & Kea Alpine Hike",
    "desc": "Scenic small-boat expedition through Milford and Doubtful Sounds with alpine hikes spotting cheeky Kea parrots.",
    "image": "/assets/images/destinations/fiordland-milford-sound-nz.jpg",
    "link": "/packages/fiordland-milford-sound-nz",
    "linkText": "Book Expedition",
    "location": "Fiordland National Park (Milford Sound), New Zealand",
    "rating": 4.9,
    "reviews": 290,
    "offprice": "10% off",
    "price": "590",
    "duration": "4 Days – 3 Nights",
    "feature": "Marine Wonder",
    "slug": "fiordland-milford-sound-nz"
  }
];

export { packages as packagesArray };
export default packages;
