// 108+ Authentic World-Class Safari Destinations
export const destinationsData = [
  {
    "id": 1,
    "slug": "serengeti-national-park",
    "name": "Serengeti National Park",
    "country": "Tanzania",
    "region": "East Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/serengeti-national-park.jpg",
    "badge": "World Wonder",
    "tagline": "Witness the Great Wildebeest Migration & the Legendary Big Five",
    "desc": "Over 14,750 km² of endless acacia savannahs, hosting the most dramatic wildlife spectacle on Earth as 1.5 million wildebeest plunge across predator-rich rivers.",
    "bestTime": "June – October",
    "sightings": [
      "Lions",
      "Cheetahs",
      "Leopards",
      "Wildebeest",
      "Elephants"
    ],
    "packagesCount": 6,
    "startingPrice": 650
  },
  {
    "id": 2,
    "slug": "maasai-mara-reserve",
    "name": "Maasai Mara National Reserve",
    "country": "Kenya",
    "region": "East Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/maasai-mara-reserve.jpg",
    "badge": "Big Five Haven",
    "tagline": "Unrivaled predator density and rich Maasai cultural heritage",
    "desc": "Renowned globally for the Mara Triangle, Musiara Marsh predator prides, and sunrise hot-air balloon safaris skimming above acacia canopies.",
    "bestTime": "July – November",
    "sightings": [
      "Lions",
      "African Elephants",
      "Black Rhinos",
      "Zebras",
      "Giraffes"
    ],
    "packagesCount": 5,
    "startingPrice": 620
  },
  {
    "id": 3,
    "slug": "kruger-national-park",
    "name": "Kruger National Park",
    "country": "South Africa",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/kruger-national-park.jpg",
    "badge": "Premier Safari",
    "tagline": "Two million hectares of pristine African wilderness and luxury lodges",
    "desc": "A breathtaking bushveld sanctuary famous for the Sabi Sand leopard territory, off-road 4x4 night tracking, and private conservation reserves.",
    "bestTime": "May – September",
    "sightings": [
      "Lions",
      "Cape Buffalo",
      "White Rhinos",
      "Wild Dogs",
      "Leopards"
    ],
    "packagesCount": 4,
    "startingPrice": 590
  },
  {
    "id": 4,
    "slug": "okavango-delta",
    "name": "Okavango Delta",
    "country": "Botswana",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/okavango-delta.jpg",
    "badge": "UNESCO Wetland",
    "tagline": "An emerald oasis in the heart of the Kalahari Desert",
    "desc": "Navigate crystalline lily-covered waterways by traditional wooden mokoro canoe alongside swimming elephants, rare sitatunga, and resident cheetah coalitions.",
    "bestTime": "May – October",
    "sightings": [
      "Cheetahs",
      "Hippos",
      "Sitatunga",
      "African Wild Dogs",
      "Fish Eagles"
    ],
    "packagesCount": 4,
    "startingPrice": 700
  },
  {
    "id": 5,
    "slug": "ngorongoro-crater",
    "name": "Ngorongoro Conservation Area",
    "country": "Tanzania",
    "region": "East Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/ngorongoro-crater.jpg",
    "badge": "Volcanic Caldera",
    "tagline": "The world's largest intact volcanic caldera teeming with 25,000 large mammals",
    "desc": "Descend 600 meters into this dramatic natural amphitheater harboring critically endangered black rhinos, golden-maned lions, and soda lakes pink with flamingos.",
    "bestTime": "Year-round",
    "sightings": [
      "Black Rhinos",
      "Lions",
      "Flamingos",
      "Hyenas",
      "Elephants"
    ],
    "packagesCount": 3,
    "startingPrice": 680
  },
  {
    "id": 6,
    "slug": "chobe-national-park",
    "name": "Chobe National Park",
    "country": "Botswana",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/chobe-national-park.jpg",
    "badge": "Elephant Kingdom",
    "tagline": "Home to Africa's largest concentrated population of over 50,000 elephants",
    "desc": "Renowned for spectacular riverfront sunset boat cruises where elephant herds swim trunk-to-trunk and cape buffalo graze along fertile floodplains.",
    "bestTime": "May – October",
    "sightings": [
      "African Elephants",
      "Cape Buffalo",
      "Lions",
      "Hippos",
      "Nile Crocodiles"
    ],
    "packagesCount": 3,
    "startingPrice": 580
  },
  {
    "id": 7,
    "slug": "amboseli-national-park",
    "name": "Amboseli National Park",
    "country": "Kenya",
    "region": "East Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/amboseli-national-park.jpg",
    "badge": "Kilimanjaro Vista",
    "tagline": "Majestic elephant herds framed against snow-capped Mount Kilimanjaro",
    "desc": "Iconic African scenery featuring great tuskers roaming across dry lakebeds and lush observation hill springs with panoramic mountain vistas.",
    "bestTime": "June – October",
    "sightings": [
      "Great Tusker Elephants",
      "Cheetahs",
      "Giraffes",
      "Zebras",
      "Pelicans"
    ],
    "packagesCount": 3,
    "startingPrice": 540
  },
  {
    "id": 8,
    "slug": "etosha-national-park",
    "name": "Etosha National Park",
    "country": "Namibia",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/etosha-national-park.jpg",
    "badge": "Great White Pan",
    "tagline": "A vast mineral salt pan where desert-adapted wildlife gathers around natural springs",
    "desc": "Gleaming white salt pans visible from space, surrounded by floodlit waterholes where black rhinos, lions, and gemsbok interact under starry desert skies.",
    "bestTime": "May – October",
    "sightings": [
      "Black Rhinos",
      "Lions",
      "Gemsbok",
      "Springbok",
      "Leopards"
    ],
    "packagesCount": 3,
    "startingPrice": 610
  },
  {
    "id": 9,
    "slug": "south-luangwa-national-park",
    "name": "South Luangwa National Park",
    "country": "Zambia",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/south-luangwa-national-park.jpg",
    "badge": "Walking Safari Birthplace",
    "tagline": "The valley of the leopard and Africa's premier on-foot tracking wilderness",
    "desc": "Pristine oxbow lagoons, dense mahogany forests, and legendary night drives with spotters uncovering incredible concentrations of leopards and Thornicroft giraffes.",
    "bestTime": "June – October",
    "sightings": [
      "Leopards",
      "Thornicroft Giraffes",
      "Hippos",
      "Crawshay Zebras",
      "Lions"
    ],
    "packagesCount": 3,
    "startingPrice": 670
  },
  {
    "id": 10,
    "slug": "mana-pools-zimbabwe",
    "name": "Mana Pools National Park",
    "country": "Zimbabwe",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/mana-pools-zimbabwe.jpg",
    "badge": "Zambezi Wilderness",
    "tagline": "Spectacular Zambezi river floodplains famed for standing elephants and wild dog packs",
    "desc": "A UNESCO wilderness known for albida tree forests where bull elephants stand tall on hind legs to pluck fruit and wild dogs hunt in open woodland.",
    "bestTime": "May – October",
    "sightings": [
      "Standing Elephants",
      "African Wild Dogs",
      "Lions",
      "Hippos",
      "Tiger Fish"
    ],
    "packagesCount": 3,
    "startingPrice": 720
  },
  {
    "id": 11,
    "slug": "samburu-national-reserve",
    "name": "Samburu National Reserve",
    "country": "Kenya",
    "region": "East Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/samburu-national-reserve.jpg",
    "badge": "Samburu Special Five",
    "tagline": "Arid northern riverbanks home to rare northern specialist wildlife",
    "desc": "Bisected by the Ewaso Ng'iro river, Samburu is celebrated for the Grevy's zebra, reticulated giraffe, Beisa oryx, Somali ostrich, and gerenuk.",
    "bestTime": "June – October & Dec – March",
    "sightings": [
      "Grevy's Zebras",
      "Reticulated Giraffes",
      "Gerenuks",
      "Leopards",
      "Lions"
    ],
    "packagesCount": 3,
    "startingPrice": 570
  },
  {
    "id": 12,
    "slug": "hwange-national-park",
    "name": "Hwange National Park",
    "country": "Zimbabwe",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/hwange-national-park.jpg",
    "badge": "Elephant Stronghold",
    "tagline": "Zimbabwe's largest national park with 40,000 elephants and rich predator prides",
    "desc": "Stretching to the sands of the Kalahari, Hwange offers dramatic underground bunker hides to photograph elephants up close at pumped waterholes.",
    "bestTime": "July – October",
    "sightings": [
      "Elephants",
      "Lions",
      "Sable Antelopes",
      "Cheetahs",
      "Wild Dogs"
    ],
    "packagesCount": 3,
    "startingPrice": 590
  },
  {
    "id": 13,
    "slug": "tarangire-national-park",
    "name": "Tarangire National Park",
    "country": "Tanzania",
    "region": "East Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/tarangire-national-park.jpg",
    "badge": "Baobab Sanctuary",
    "tagline": "Colossal ancient baobabs and massive elephant migrations along the Tarangire River",
    "desc": "Famous for colossal thousand-year-old baobab trees, tree-climbing lions, and dry season concentrations of over 3,000 elephants.",
    "bestTime": "June – October",
    "sightings": [
      "Elephants",
      "Tree-climbing Lions",
      "Leopards",
      "Oryx",
      "Baobab Vistas"
    ],
    "packagesCount": 3,
    "startingPrice": 530
  },
  {
    "id": 14,
    "slug": "lake-nakuru-national-park",
    "name": "Lake Nakuru National Park",
    "country": "Kenya",
    "region": "East Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/lake-nakuru-national-park.jpg",
    "badge": "Rhino & Bird Haven",
    "tagline": "Alkaline Great Rift Valley lake fringed by millions of pink flamingos and rhinos",
    "desc": "A compact sanctuary hosting one of Kenya's most successful black and white rhino sanctuaries, along with Rothschild giraffes and waterbirds.",
    "bestTime": "Year-round",
    "sightings": [
      "White Rhinos",
      "Black Rhinos",
      "Lesser Flamingos",
      "Rothschild Giraffes",
      "Leopards"
    ],
    "packagesCount": 2,
    "startingPrice": 480
  },
  {
    "id": 15,
    "slug": "queen-elizabeth-national-park",
    "name": "Queen Elizabeth National Park",
    "country": "Uganda",
    "region": "East Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/queen-elizabeth-national-park.jpg",
    "badge": "Tree-Climbing Lions",
    "tagline": "Ishasha's famous fig tree lions and Kazinga Channel boat cruises",
    "desc": "Diverse savannahs, volcanic craters, and the Kazinga Channel which boasts the highest concentration of hippos in Africa.",
    "bestTime": "January – February & June – July",
    "sightings": [
      "Tree-climbing Lions",
      "Hippos",
      "Nile Crocodiles",
      "Chimpanzees",
      "Elephants"
    ],
    "packagesCount": 3,
    "startingPrice": 560
  },
  {
    "id": 16,
    "slug": "madikwe-game-reserve",
    "name": "Madikwe Game Reserve",
    "country": "South Africa",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/madikwe-game-reserve.jpg",
    "badge": "Malaria-Free Big 5",
    "tagline": "Premier malaria-free wildlife reserve ideal for family luxury safaris",
    "desc": "Located on the border of Botswana, Madikwe encompasses rocky hills, Kalahari sands, and savannahs known for successful wild dog packs.",
    "bestTime": "May – September",
    "sightings": [
      "African Wild Dogs",
      "Lions",
      "Cheetahs",
      "Brown Hyenas",
      "White Rhinos"
    ],
    "packagesCount": 3,
    "startingPrice": 630
  },
  {
    "id": 17,
    "slug": "phinda-private-game-reserve",
    "name": "Phinda Private Game Reserve",
    "country": "South Africa",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/phinda-private-game-reserve.jpg",
    "badge": "Seven Ecosystems",
    "tagline": "Seven distinct habitats including rare sand forests and cheetah breeding grounds",
    "desc": "Renowned globally for close-up cheetah encounters, black rhino tracking on foot, and dramatic views over Zululand.",
    "bestTime": "April – September",
    "sightings": [
      "Cheetahs",
      "Black Rhinos",
      "Pangolins",
      "Lions",
      "Leopards"
    ],
    "packagesCount": 3,
    "startingPrice": 760
  },
  {
    "id": 18,
    "slug": "sabi-sand-game-reserve",
    "name": "Sabi Sand Game Reserve",
    "country": "South Africa",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/sabi-sand-game-reserve.jpg",
    "badge": "Leopard Dynasty",
    "tagline": "Africa's most famous private reserve sharing unfenced borders with Kruger",
    "desc": "Unrivaled up-close leopard viewing, luxury tented camps, and exclusive off-road tracker rights in the pristine southern African lowveld.",
    "bestTime": "Year-round (May – Sep dry best)",
    "sightings": [
      "Leopards",
      "Lions",
      "Rhinos",
      "Elephants",
      "Cape Buffalo"
    ],
    "packagesCount": 4,
    "startingPrice": 880
  },
  {
    "id": 19,
    "slug": "tsavo-national-parks",
    "name": "Tsavo East & West National Parks",
    "country": "Kenya",
    "region": "East Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/tsavo-national-parks.jpg",
    "badge": "Red Elephants",
    "tagline": "Dramatic volcanic landscapes and famous red-dust elephants of Tsavo",
    "desc": "Kenya's largest protected wilderness featuring Mzima Springs underwater hippo viewing chambers, Shetani lava flows, and red-dusted elephant herds.",
    "bestTime": "June – October & Jan – Feb",
    "sightings": [
      "Red-Dust Elephants",
      "Lions",
      "Hippos",
      "Oryx",
      "Gerenuk"
    ],
    "packagesCount": 3,
    "startingPrice": 510
  },
  {
    "id": 20,
    "slug": "moremi-game-reserve",
    "name": "Moremi Game Reserve",
    "country": "Botswana",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/moremi-game-reserve.jpg",
    "badge": "Okavango Jewel",
    "tagline": "The only officially proclaimed game reserve inside the Okavango Delta",
    "desc": "Chief's Island and mopane woodlands harboring one of Africa's densest wildlife populations including endangered wild dogs and black rhinos.",
    "bestTime": "July – October",
    "sightings": [
      "Wild Dogs",
      "Leopards",
      "Lions",
      "Cheetahs",
      "Red Lechwe"
    ],
    "packagesCount": 3,
    "startingPrice": 740
  },
  {
    "id": 21,
    "slug": "lower-zambezi-national-park",
    "name": "Lower Zambezi National Park",
    "country": "Zambia",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/lower-zambezi-national-park.jpg",
    "badge": "River Wilderness",
    "tagline": "Dramatic escarpment drop-offs meeting the wide, lazy waters of the Zambezi River",
    "desc": "Canoe past swimming elephants and pods of hippos with the Zambezi escarpment rising steeply in the background.",
    "bestTime": "May – October",
    "sightings": [
      "Elephants",
      "Hippos",
      "Leopards",
      "Tigerfish",
      "African Fish Eagles"
    ],
    "packagesCount": 3,
    "startingPrice": 690
  },
  {
    "id": 22,
    "slug": "kafue-national-park",
    "name": "Kafue National Park",
    "country": "Zambia",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/kafue-national-park.jpg",
    "badge": "Untamed Giant",
    "tagline": "Zambia's oldest and largest park covering 22,400 km² of pristine wilderness",
    "desc": "Busanga Plains flooded grasslands attracting thousands of red lechwe, wildebeest, and famous tree-climbing lions.",
    "bestTime": "July – October",
    "sightings": [
      "Busanga Lions",
      "Cheetahs",
      "Roan Antelopes",
      "Sables",
      "Wild Dogs"
    ],
    "packagesCount": 3,
    "startingPrice": 660
  },
  {
    "id": 23,
    "slug": "liuwa-plain-national-park",
    "name": "Liuwa Plain National Park",
    "country": "Zambia",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/liuwa-plain-national-park.jpg",
    "badge": "Second Largest Migration",
    "tagline": "Africa's second largest wildebeest migration and legendary hyena clans",
    "desc": "Sweeping golden grasslands where 40,000 blue wildebeest migrate annually alongside massive clans of spotted hyenas and wild dogs.",
    "bestTime": "October – December & May – July",
    "sightings": [
      "Wildebeest Migration",
      "Spotted Hyenas",
      "Cheetahs",
      "Wild Dogs",
      "Crowned Cranes"
    ],
    "packagesCount": 2,
    "startingPrice": 780
  },
  {
    "id": 24,
    "slug": "gonarezhou-national-park",
    "name": "Gonarezhou National Park",
    "country": "Zimbabwe",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/gonarezhou-national-park.jpg",
    "badge": "Chilojo Cliffs",
    "tagline": "Place of Many Elephants and red sandstone Chilojo Cliffs",
    "desc": "Part of the Great Limpopo Transfrontier Park, famed for colossal sandstone cliffs overlooking the Runde River and rugged wilderness.",
    "bestTime": "April – October",
    "sightings": [
      "Elephants",
      "Nyala",
      "Wild Dogs",
      "Lions",
      "Giraffes"
    ],
    "packagesCount": 2,
    "startingPrice": 620
  },
  {
    "id": 25,
    "slug": "hluhluwe-imfolozi-park",
    "name": "Hluhluwe-iMfolozi Park",
    "country": "South Africa",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/hluhluwe-imfolozi-park.jpg",
    "badge": "Rhino Conservation Cradle",
    "tagline": "Africa's oldest proclaimed nature reserve that saved the White Rhino from extinction",
    "desc": "Rolling green hills of Zululand famous for 'Operation Rhino' and incredible close-quarter black and white rhino encounters.",
    "bestTime": "May – September",
    "sightings": [
      "White Rhinos",
      "Black Rhinos",
      "Lions",
      "Cheetahs",
      "Nyala"
    ],
    "packagesCount": 3,
    "startingPrice": 520
  },
  {
    "id": 26,
    "slug": "addo-elephant-national-park",
    "name": "Addo Elephant National Park",
    "country": "South Africa",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/addo-elephant-national-park.jpg",
    "badge": "Big Seven Reserve",
    "tagline": "The world's only reserve hosting Africa's 'Big Seven' including Great White Sharks & Whales",
    "desc": "Expanding from thick spekboom elephant habitat in the Eastern Cape all the way to coastal marine islands with penguins and marine predators.",
    "bestTime": "May – September",
    "sightings": [
      "African Elephants",
      "Lions",
      "Flightless Dung Beetles",
      "Great White Sharks",
      "Southern Right Whales"
    ],
    "packagesCount": 3,
    "startingPrice": 490
  },
  {
    "id": 27,
    "slug": "timbavati-game-reserve",
    "name": "Timbavati Private Nature Reserve",
    "country": "South Africa",
    "region": "Southern Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/timbavati-game-reserve.jpg",
    "badge": "White Lions of Timbavati",
    "tagline": "The natural home of the legendary indigenous White Lions",
    "desc": "Shares an unfenced 50km boundary with Kruger National Park, renowned for white lion genetics, wild dogs, and exclusive private lodges.",
    "bestTime": "April – September",
    "sightings": [
      "White Lions",
      "Tawny Lions",
      "Leopards",
      "Elephants",
      "White Rhinos"
    ],
    "packagesCount": 3,
    "startingPrice": 790
  },
  {
    "id": 28,
    "slug": "kidepo-valley-national-park",
    "name": "Kidepo Valley National Park",
    "country": "Uganda",
    "region": "East Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/kidepo-valley-national-park.jpg",
    "badge": "Untouched Eden",
    "tagline": "Uganda's most remote, spectacular savannah tucked into the Karamoja borderlands",
    "desc": "Rugged savannah valley bordered by the Morungole mountain range, famous for massive buffalo herds, cheetahs, and ostriches.",
    "bestTime": "September – March",
    "sightings": [
      "Cape Buffalo Herds",
      "Cheetahs",
      "Lions",
      "Ostriches",
      "Bat-eared Foxes"
    ],
    "packagesCount": 2,
    "startingPrice": 650
  },
  {
    "id": 29,
    "slug": "selous-nyerere-national-park",
    "name": "Nyerere National Park (Selous)",
    "country": "Tanzania",
    "region": "East Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/selous-nyerere-national-park.jpg",
    "badge": "Rufiji River Kingdom",
    "tagline": "Africa's largest standalone national park bisected by the mighty Rufiji River",
    "desc": "A massive wilderness of miombo woodlands, oxbow lakes, and sandbanks where boat safaris yield close encounters with hippos and wild dogs.",
    "bestTime": "June – October",
    "sightings": [
      "African Wild Dogs",
      "Lions",
      "Hippos",
      "Nile Crocodiles",
      "Elephants"
    ],
    "packagesCount": 3,
    "startingPrice": 620
  },
  {
    "id": 30,
    "slug": "ruaha-national-park",
    "name": "Ruaha National Park",
    "country": "Tanzania",
    "region": "East Africa",
    "category": "African Savannahs",
    "image": "/assets/images/destinations/ruaha-national-park.jpg",
    "badge": "Predator Stronghold",
    "tagline": "Tanzania's wild southern giant hosting 10% of the world's surviving lions",
    "desc": "Baobab-studded rocky landscapes around the Great Ruaha River, famous for super-prides of 20+ lions and rare greater kudu antelopes.",
    "bestTime": "June – October",
    "sightings": [
      "Super Prides of Lions",
      "Greater Kudu",
      "Leopards",
      "Cheetahs",
      "Wild Dogs"
    ],
    "packagesCount": 3,
    "startingPrice": 640
  },
  {
    "id": 31,
    "slug": "bandhavgarh-tiger-reserve",
    "name": "Bandhavgarh National Park",
    "country": "India",
    "region": "Central India",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/bandhavgarh-tiger-reserve.jpg",
    "badge": "Royal Bengal Tigers",
    "tagline": "The world's highest density of wild Royal Bengal Tigers",
    "desc": "Ancient 2,000-year-old fort ramparts, towering sal trees, and bamboo valleys where legendary tiger dynasties roam across Tala, Magdhi, and Khitauli zones.",
    "bestTime": "October – May",
    "sightings": [
      "Bengal Tigers",
      "Leopards",
      "Sloth Bears",
      "Chital Deer",
      "Gaur"
    ],
    "packagesCount": 6,
    "startingPrice": 480
  },
  {
    "id": 32,
    "slug": "kaziranga-rhino-sanctuary",
    "name": "Kaziranga National Park",
    "country": "India",
    "region": "Northeast India",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/kaziranga-rhino-sanctuary.jpg",
    "badge": "Great One-Horned Rhino",
    "tagline": "Two-thirds of the world's Great One-Horned Rhinoceros population",
    "desc": "Lush Brahmaputra floodplains, towering elephant grass, and dense wetlands hosting rhinos, wild water buffalo, swamp deer, and Bengal tigers.",
    "bestTime": "November – April",
    "sightings": [
      "One-Horned Rhinos",
      "Wild Water Buffalo",
      "Swamp Deer",
      "Tigers",
      "Elephants"
    ],
    "packagesCount": 4,
    "startingPrice": 420
  },
  {
    "id": 33,
    "slug": "ranthambore-national-park",
    "name": "Ranthambore National Park",
    "country": "India",
    "region": "North India",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/ranthambore-national-park.jpg",
    "badge": "Fortress Tigers",
    "tagline": "Majestic tigers hunting amid 10th-century ruins and lotus lakes",
    "desc": "Iconic hunting grounds of the Maharajas of Jaipur, where tigers stalk sambar deer beneath ancient battlements, cenotaphs, and Padam Talao lake.",
    "bestTime": "October – May",
    "sightings": [
      "Bengal Tigers",
      "Indian Leopards",
      "Marsh Crocodiles",
      "Striped Hyenas",
      "Sambar"
    ],
    "packagesCount": 5,
    "startingPrice": 460
  },
  {
    "id": 34,
    "slug": "kanha-national-park",
    "name": "Kanha National Park",
    "country": "India",
    "region": "Central India",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/kanha-national-park.jpg",
    "badge": "Jungle Book Realm",
    "tagline": "Rudyard Kipling's inspiration and sanctuary of the rare Hardground Barasingha",
    "desc": "Vast horseshoe valley of lush sal and bamboo forests, rolling meadows, and clear streams harboring tigers, leopards, and the revived swamp deer.",
    "bestTime": "October – June",
    "sightings": [
      "Bengal Tigers",
      "Hardground Barasingha",
      "Indian Wild Dogs (Dhole)",
      "Gaur",
      "Sloth Bears"
    ],
    "packagesCount": 4,
    "startingPrice": 470
  },
  {
    "id": 35,
    "slug": "jim-corbett-national-park",
    "name": "Jim Corbett National Park",
    "country": "India",
    "region": "North India",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/jim-corbett-national-park.jpg",
    "badge": "First National Park",
    "tagline": "Nestled in the Himalayan foothills along the sparkling Ramganga River",
    "desc": "India's oldest national park, famous for the historic Dhikala forest rest house, wild elephant herds crossing river pebbles, and elusive forest tigers.",
    "bestTime": "November – June",
    "sightings": [
      "Bengal Tigers",
      "Wild Asian Elephants",
      "Gharials",
      "King Cobras",
      "Otters"
    ],
    "packagesCount": 4,
    "startingPrice": 430
  },
  {
    "id": 36,
    "slug": "tadoba-andhari-reserve",
    "name": "Tadoba Andhari Tiger Reserve",
    "country": "India",
    "region": "Central India",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/tadoba-andhari-reserve.jpg",
    "badge": "The Jewel of Vidarbha",
    "tagline": "India's tiger factory with guaranteed sightings around perennial waterholes",
    "desc": "Teak and bamboo jungles surrounding Tadoba lake and Erai reservoir, famous for bold tiger mothers raising cubs in open view.",
    "bestTime": "October – June",
    "sightings": [
      "Bengal Tigers",
      "Sloth Bears",
      "Indian Leopards",
      "Marsh Crocodiles",
      "Barking Deer"
    ],
    "packagesCount": 4,
    "startingPrice": 450
  },
  {
    "id": 37,
    "slug": "gir-lion-sanctuary",
    "name": "Gir National Park & Sanctuary",
    "country": "India",
    "region": "West India",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/gir-lion-sanctuary.jpg",
    "badge": "Asiatic Lions",
    "tagline": "The last surviving refuge of the pure Asiatic Lion on Earth",
    "desc": "Rugged deciduous teak forest and scrublands in Gujarat, where over 600 wild Asiatic lions roam alongside leopards and Maldhari pastoralists.",
    "bestTime": "December – April",
    "sightings": [
      "Asiatic Lions",
      "Indian Leopards",
      "Chowsingha (Four-horned Antelope)",
      "Spotted Deer",
      "Striped Hyenas"
    ],
    "packagesCount": 3,
    "startingPrice": 410
  },
  {
    "id": 38,
    "slug": "nagarhole-kabini-reserve",
    "name": "Nagarhole National Park (Kabini)",
    "country": "India",
    "region": "South India",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/nagarhole-kabini-reserve.jpg",
    "badge": "Kabini Black Panther",
    "tagline": "Lush Western Ghats forests famous for the melanistic Black Panther and Asian Elephants",
    "desc": "Pristine Nilgiri Biosphere reserve along the Kabini River, hosting the famous black panther 'Saya', dense leopard populations, and herds of elephants.",
    "bestTime": "October – May",
    "sightings": [
      "Black Panthers",
      "Bengal Tigers",
      "Asian Elephants",
      "Indian Leopards",
      "Dholes"
    ],
    "packagesCount": 4,
    "startingPrice": 510
  },
  {
    "id": 39,
    "slug": "pench-tiger-reserve",
    "name": "Pench Tiger Reserve",
    "country": "India",
    "region": "Central India",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/pench-tiger-reserve.jpg",
    "badge": "Mowgli's Homeland",
    "tagline": "Undulating hills and teak forests along the meandering Pench River",
    "desc": "Straddling Madhya Pradesh and Maharashtra, Pench is celebrated for thriving tiger families, leopards, and large herds of chital and sambar.",
    "bestTime": "October – June",
    "sightings": [
      "Bengal Tigers",
      "Indian Wild Dogs",
      "Leopards",
      "Jungle Cats",
      "Gaur"
    ],
    "packagesCount": 3,
    "startingPrice": 440
  },
  {
    "id": 40,
    "slug": "panna-national-park",
    "name": "Panna National Park",
    "country": "India",
    "region": "Central India",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/panna-national-park.jpg",
    "badge": "Tiger Reintroduction Wonder",
    "tagline": "Deep gorges, teak forests, and the sparkling Ken River",
    "desc": "Global model for tiger conservation following a historic reintroduction program, renowned for vulture cliffs, boat safaris, and gharial sanctuaries.",
    "bestTime": "November – May",
    "sightings": [
      "Bengal Tigers",
      "Vultures",
      "Sloth Bears",
      "Chinkara",
      "Gharials"
    ],
    "packagesCount": 3,
    "startingPrice": 420
  },
  {
    "id": 41,
    "slug": "satpura-tiger-reserve",
    "name": "Satpura Tiger Reserve",
    "country": "India",
    "region": "Central India",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/satpura-tiger-reserve.jpg",
    "badge": "Walking Tiger Jungle",
    "tagline": "India's only tiger reserve offering walking safaris, canoeing, and night drives",
    "desc": "Rugged sandstone peaks, narrow gorges, and Denwa backwaters providing unmatched tranquil wildlife encounters away from tourist crowds.",
    "bestTime": "October – April",
    "sightings": [
      "Sloth Bears",
      "Leopards",
      "Indian Giant Squirrels",
      "Tigers",
      "Crocodiles"
    ],
    "packagesCount": 3,
    "startingPrice": 490
  },
  {
    "id": 42,
    "slug": "dudhwa-national-park",
    "name": "Dudhwa National Park",
    "country": "India",
    "region": "North India (Terai)",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/dudhwa-national-park.jpg",
    "badge": "Terai Arc Ecosystem",
    "tagline": "Dense sal forests and tall grasslands harboring tigers, rhinos, and swamp deer",
    "desc": "Bordering Nepal, Dudhwa preserves the pristine Terai floodplains, sheltering one-horned rhinos, breeding tigers, and over 450 bird species.",
    "bestTime": "November – May",
    "sightings": [
      "One-Horned Rhinos",
      "Bengal Tigers",
      "Swamp Deer",
      "Hispid Hares",
      "Bengal Floricans"
    ],
    "packagesCount": 2,
    "startingPrice": 410
  },
  {
    "id": 43,
    "slug": "manas-national-park",
    "name": "Manas National Park",
    "country": "India",
    "region": "Northeast India (Assam)",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/manas-national-park.jpg",
    "badge": "UNESCO Biosphere",
    "tagline": "Pristine Himalayan foothills bordering the Kingdom of Bhutan",
    "desc": "A contiguous transboundary reserve famous for pygmy hogs, golden langurs, wild water buffalo, and royal Bengal tigers along the crystal Manas river.",
    "bestTime": "November – April",
    "sightings": [
      "Golden Langurs",
      "Pygmy Hogs",
      "Asian Elephants",
      "Bengal Tigers",
      "One-Horned Rhinos"
    ],
    "packagesCount": 3,
    "startingPrice": 430
  },
  {
    "id": 44,
    "slug": "periyar-national-park",
    "name": "Periyar National Park",
    "country": "India",
    "region": "South India (Kerala)",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/periyar-national-park.jpg",
    "badge": "Western Ghats Haven",
    "tagline": "Lake safaris amid evergreen Cardamom Hills and wild elephant herds",
    "desc": "A scenic reservoir in the Western Ghats where wild elephants and bison congregate on the lakeshores to bathe and feed.",
    "bestTime": "September – April",
    "sightings": [
      "Asian Elephants",
      "Gaur (Indian Bison)",
      "Nilgiri Langurs",
      "Tigers",
      "Malabar Giant Squirrels"
    ],
    "packagesCount": 3,
    "startingPrice": 380
  },
  {
    "id": 45,
    "slug": "bandipur-national-park",
    "name": "Bandipur National Park",
    "country": "India",
    "region": "South India (Karnataka)",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/bandipur-national-park.jpg",
    "badge": "Nilgiri Tiger Reserve",
    "tagline": "Dense deciduous forests nestled at the foot of the Nilgiri Hills",
    "desc": "Part of India's largest contiguous forest complex, boasting thriving populations of tigers, leopards, gaur, and wild elephants.",
    "bestTime": "October – May",
    "sightings": [
      "Bengal Tigers",
      "Indian Leopards",
      "Asian Elephants",
      "Gaur",
      "Sloth Bears"
    ],
    "packagesCount": 3,
    "startingPrice": 420
  },
  {
    "id": 46,
    "slug": "sunderbans-mangrove-delta",
    "name": "Sundarbans National Park",
    "country": "India",
    "region": "East India",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/sunderbans-mangrove-delta.jpg",
    "badge": "Mangrove Tigers",
    "tagline": "The world's largest mangrove delta where swimming tigers rule the tides",
    "desc": "Tidal halophytic mangrove swamps where Royal Bengal tigers have adapted to saltwater swimming and hunting spotted deer along muddy estuaries.",
    "bestTime": "November – March",
    "sightings": [
      "Swimming Bengal Tigers",
      "Estuarine Crocodiles",
      "Gangetic Dolphins",
      "Water Monitors",
      "Kingfishers"
    ],
    "packagesCount": 3,
    "startingPrice": 390
  },
  {
    "id": 47,
    "slug": "keoladeo-national-park",
    "name": "Keoladeo Ghana National Park",
    "country": "India",
    "region": "North India (Bharatpur)",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/keoladeo-national-park.jpg",
    "badge": "Avian Wonderland",
    "tagline": "World Heritage wetland hosting over 370 resident and migratory bird species",
    "desc": "A man-made freshwater wetland explored quietly by cycle-rickshaws driven by certified local ornithologist guides.",
    "bestTime": "October – March",
    "sightings": [
      "Siberian Cranes",
      "Painted Storks",
      "Pelicans",
      "Sambar Deer",
      "Pythons"
    ],
    "packagesCount": 2,
    "startingPrice": 290
  },
  {
    "id": 48,
    "slug": "silent-valley-national-park",
    "name": "Silent Valley National Park",
    "country": "India",
    "region": "South India (Kerala)",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/silent-valley-national-park.jpg",
    "badge": "Virgin Rainforest",
    "tagline": "Untouched tropical rainforest and sanctuary of the Lion-tailed Macaque",
    "desc": "Shielded in the Kundali Hills, Silent Valley preserves continuous virgin primary forest with legendary silence devoid of cicadas.",
    "bestTime": "December – April",
    "sightings": [
      "Lion-tailed Macaques",
      "Nilgiri Tahrs",
      "Malabar Giant Squirrels",
      "Tigers",
      "Hornbills"
    ],
    "packagesCount": 2,
    "startingPrice": 350
  },
  {
    "id": 49,
    "slug": "namdapha-national-park",
    "name": "Namdapha National Park",
    "country": "India",
    "region": "Northeast India (Arunachal)",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/namdapha-national-park.jpg",
    "badge": "Four Big Cats Realm",
    "tagline": "The only park in the world harboring Tigers, Leopards, Snow Leopards, and Clouded Leopards",
    "desc": "Remote rainforest rising to sub-alpine snow zones near the Myanmar border, teeming with red pandas, hoolock gibbons, and clouded leopards.",
    "bestTime": "October – March",
    "sightings": [
      "Clouded Leopards",
      "Red Pandas",
      "Hoolock Gibbons",
      "Snow Leopards",
      "Bengal Tigers"
    ],
    "packagesCount": 2,
    "startingPrice": 680
  },
  {
    "id": 50,
    "slug": "great-himalayan-national-park",
    "name": "Great Himalayan National Park",
    "country": "India",
    "region": "North India (Himachal)",
    "category": "Mountain & High Altitude",
    "image": "/assets/images/destinations/great-himalayan-national-park.jpg",
    "badge": "UNESCO Alpine Sanctuary",
    "tagline": "Glaciated alpine peaks and habitat of the Western Tragopan and Musk Deer",
    "desc": "Untouched Himalayan catchments covered in deodar and oak forests rising to glacial cirques, home to elusive snow leopards and Himalayan black bears.",
    "bestTime": "April – June & September – November",
    "sightings": [
      "Western Tragopans",
      "Himalayan Musk Deer",
      "Blue Sheep",
      "Snow Leopards",
      "Himalayan Monals"
    ],
    "packagesCount": 2,
    "startingPrice": 560
  },
  {
    "id": 51,
    "slug": "chitwan-national-park-nepal",
    "name": "Chitwan National Park",
    "country": "Nepal",
    "region": "Terai Lowlands",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/chitwan-national-park-nepal.jpg",
    "badge": "Himalayan Foothill Jungle",
    "tagline": "One-horned Rhinos and Bengal Tigers in the shadow of the Himalayas",
    "desc": "Lush subtropical lowlands where the Rapti River flows past sal forests sheltering rhinos, gharials, tigers, and hundreds of bird species.",
    "bestTime": "October – March",
    "sightings": [
      "One-Horned Rhinos",
      "Bengal Tigers",
      "Gharial Crocodiles",
      "Sloth Bears",
      "Asian Elephants"
    ],
    "packagesCount": 3,
    "startingPrice": 380
  },
  {
    "id": 52,
    "slug": "bardia-national-park",
    "name": "Bardia National Park",
    "country": "Nepal",
    "region": "Western Terai",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/bardia-national-park.jpg",
    "badge": "Wild West Nepal",
    "tagline": "Nepal's largest untouched wilderness famous for wild tigers and river dolphins",
    "desc": "A remote haven along the Karnali River where pristine sal forests offer some of Asia's highest chances of wild tiger sightings on walking safaris.",
    "bestTime": "October – April",
    "sightings": [
      "Bengal Tigers",
      "One-Horned Rhinos",
      "Gangetic Dolphins",
      "Wild Elephants",
      "Swamp Deer"
    ],
    "packagesCount": 3,
    "startingPrice": 420
  },
  {
    "id": 53,
    "slug": "mudumalai-national-park",
    "name": "Mudumalai National Park",
    "country": "India",
    "region": "South India (Tamil Nadu)",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/mudumalai-national-park.jpg",
    "badge": "Nilgiri Corridor",
    "tagline": "Vital elephant migration corridor connecting the Eastern and Western Ghats",
    "desc": "Undulating hills covered with teak, bamboo, and rosewood, home to dense populations of Asian elephants, leopards, and Bengal tigers.",
    "bestTime": "October – May",
    "sightings": [
      "Asian Elephants",
      "Bengal Tigers",
      "Indian Leopards",
      "Gaur",
      "Stripe-necked Mongooses"
    ],
    "packagesCount": 3,
    "startingPrice": 390
  },
  {
    "id": 54,
    "slug": "anamalai-tiger-reserve",
    "name": "Anamalai Tiger Reserve (Topslip)",
    "country": "India",
    "region": "South India (Tamil Nadu)",
    "category": "Indian Jungles",
    "image": "/assets/images/destinations/anamalai-tiger-reserve.jpg",
    "badge": "Elephant Hills",
    "tagline": "High tropical rainforests and cardamom plantations teeming with endemic wildlife",
    "desc": "Steep rainforest slopes harboring rare Nilgiri tahrs, lion-tailed macaques, giant squirrels, and elusive forest leopards.",
    "bestTime": "December – June",
    "sightings": [
      "Lion-tailed Macaques",
      "Nilgiri Tahrs",
      "Indian Leopards",
      "Elephants",
      "Hornbills"
    ],
    "packagesCount": 2,
    "startingPrice": 370
  },
  {
    "id": 55,
    "slug": "eravikulam-national-park",
    "name": "Eravikulam National Park",
    "country": "India",
    "region": "South India (Munnar)",
    "category": "Mountain & High Altitude",
    "image": "/assets/images/destinations/eravikulam-national-park.jpg",
    "badge": "Nilgiri Tahr Sanctuary",
    "tagline": "Rolling shola grasslands home to the largest surviving population of Nilgiri Tahr",
    "desc": "High-altitude rolling shola-grassland ecosystem in the High Ranges of Munnar, blooming with rare Neelakurinji flowers every twelve years.",
    "bestTime": "September – May",
    "sightings": [
      "Nilgiri Tahrs",
      "Golden Jackals",
      "Sambars",
      "Leopards",
      "Atlas Moths"
    ],
    "packagesCount": 2,
    "startingPrice": 310
  },
  {
    "id": 56,
    "slug": "yala-national-park",
    "name": "Yala National Park",
    "country": "Sri Lanka",
    "region": "South Asia",
    "category": "Sri Lankan Sanctuaries",
    "image": "/assets/images/destinations/yala-national-park.jpg",
    "badge": "Leopard Capital of Asia",
    "tagline": "The world's highest density of Sri Lankan Leopards",
    "desc": "Coastal thorn scrub, towering granite monoliths, and freshwater lagoons where leopards lounge on rocky outcroppings overlooking the Indian Ocean.",
    "bestTime": "February – July",
    "sightings": [
      "Sri Lankan Leopards",
      "Sloth Bears",
      "Asian Elephants",
      "Mugger Crocodiles",
      "Spotted Deer"
    ],
    "packagesCount": 4,
    "startingPrice": 380
  },
  {
    "id": 57,
    "slug": "wilpattu-national-park",
    "name": "Wilpattu National Park",
    "country": "Sri Lanka",
    "region": "South Asia",
    "category": "Sri Lankan Sanctuaries",
    "image": "/assets/images/destinations/wilpattu-national-park.jpg",
    "badge": "Land of Willus",
    "tagline": "Sri Lanka's largest and oldest national park with natural sand-rimmed water basins",
    "desc": "Ancient dry zone forests dotted with nearly 60 natural rainwater lakes (willus), offering secluded tracking for sloth bears and leopards.",
    "bestTime": "February – October",
    "sightings": [
      "Sri Lankan Leopards",
      "Sloth Bears",
      "Asian Elephants",
      "Barking Deer",
      "Painted Storks"
    ],
    "packagesCount": 3,
    "startingPrice": 390
  },
  {
    "id": 58,
    "slug": "udawalawe-national-park",
    "name": "Udawalawe National Park",
    "country": "Sri Lanka",
    "region": "South Asia",
    "category": "Sri Lankan Sanctuaries",
    "image": "/assets/images/destinations/udawalawe-national-park.jpg",
    "badge": "Elephant Gathering",
    "tagline": "Guaranteed wild elephant sightings around a scenic reservoir",
    "desc": "Open savannah grasslands reminiscent of East Africa, home to over 500 wild elephants and the renowned Elephant Transit Home rehabilitation project.",
    "bestTime": "Year-round",
    "sightings": [
      "Asian Elephants",
      "Water Buffalo",
      "Toque Macaques",
      "Jackals",
      "Changeable Hawk-Eagles"
    ],
    "packagesCount": 3,
    "startingPrice": 340
  },
  {
    "id": 59,
    "slug": "minneriya-national-park",
    "name": "Minneriya National Park",
    "country": "Sri Lanka",
    "region": "South Asia",
    "category": "Sri Lankan Sanctuaries",
    "image": "/assets/images/destinations/minneriya-national-park.jpg",
    "badge": "The Great Gathering",
    "tagline": "Witness 300+ Asian elephants assemble on the ancient reservoir bed",
    "desc": "During the dry season, hundreds of elephants congregate around the 3rd-century Minneriya tank to graze on fresh grass, socialize, and bathe.",
    "bestTime": "July – October",
    "sightings": [
      "Asian Elephants (The Gathering)",
      "Purple-faced Langurs",
      "Painted Storks",
      "Crested Serpent Eagles",
      "Sambar"
    ],
    "packagesCount": 3,
    "startingPrice": 360
  },
  {
    "id": 60,
    "slug": "sinharaja-forest-reserve",
    "name": "Sinharaja Forest Reserve",
    "country": "Sri Lanka",
    "region": "South Asia",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/sinharaja-forest-reserve.jpg",
    "badge": "UNESCO Tropical Rainforest",
    "tagline": "The last viable virgin primary rainforest in Sri Lanka with immense endemism",
    "desc": "Dense canopy dripping with tropical mist, home to mixed-species bird feeding flocks, purple-faced langurs, and rare endemic reptiles and amphibians.",
    "bestTime": "December – April & August – September",
    "sightings": [
      "Purple-faced Langurs",
      "Sri Lanka Blue Magpies",
      "Green Pit Vipers",
      "Giant Squirrels",
      "Tree Frogs"
    ],
    "packagesCount": 2,
    "startingPrice": 320
  },
  {
    "id": 61,
    "slug": "bundala-national-park",
    "name": "Bundala National Park",
    "country": "Sri Lanka",
    "region": "South Asia",
    "category": "Sri Lankan Sanctuaries",
    "image": "/assets/images/destinations/bundala-national-park.jpg",
    "badge": "Ramsar Wetland Wonder",
    "tagline": "Coastal lagoons hosting thousands of migratory flamingos and sea turtles",
    "desc": "A UNESCO Biosphere Reserve on the southern coast comprising five shallow brackish lagoons where flamingos, pelicans, and waders winter.",
    "bestTime": "September – March",
    "sightings": [
      "Greater Flamingos",
      "Estuarine Crocodiles",
      "Sea Turtles",
      "Elephants",
      "Spot-billed Pelicans"
    ],
    "packagesCount": 2,
    "startingPrice": 310
  },
  {
    "id": 62,
    "slug": "kumana-national-park",
    "name": "Kumana National Park",
    "country": "Sri Lanka",
    "region": "South Asia",
    "category": "Sri Lankan Sanctuaries",
    "image": "/assets/images/destinations/kumana-national-park.jpg",
    "badge": "Bird Paradise",
    "tagline": "Yala East's secluded bird sanctuary and breeding mangrove swamp",
    "desc": "Renowned for its large mangrove swamp where thousands of waterbirds nest from May to July, along with leopards, elephants, and bears.",
    "bestTime": "April – July",
    "sightings": [
      "Black-necked Storks",
      "Sri Lankan Leopards",
      "Eurasian Spoonbills",
      "Elephants",
      "White Ibises"
    ],
    "packagesCount": 2,
    "startingPrice": 330
  },
  {
    "id": 63,
    "slug": "wasgamuwa-national-park",
    "name": "Wasgamuwa National Park",
    "country": "Sri Lanka",
    "region": "South Asia",
    "category": "Sri Lankan Sanctuaries",
    "image": "/assets/images/destinations/wasgamuwa-national-park.jpg",
    "badge": "Bear & Elephant Haven",
    "tagline": "Pristine dry-evergreen jungle bordered by the Mahaweli River",
    "desc": "One of Sri Lanka's least crowded parks, offering high chances of encountering wild sloth bears foraging for palu fruit and elephant herds.",
    "bestTime": "November – May",
    "sightings": [
      "Sloth Bears",
      "Asian Elephants",
      "Water Buffalo",
      "Marsh Crocodiles",
      "Axis Deer"
    ],
    "packagesCount": 2,
    "startingPrice": 340
  },
  {
    "id": 64,
    "slug": "horton-plains-national-park",
    "name": "Horton Plains National Park",
    "country": "Sri Lanka",
    "region": "Central Highlands",
    "category": "Mountain & High Altitude",
    "image": "/assets/images/destinations/horton-plains-national-park.jpg",
    "badge": "World's End Cliff",
    "tagline": "Misty cloud forests, Baker's Falls, and the sheer World's End precipice",
    "desc": "A plateau at 2,200m altitude dominated by montane grasslands and cloud forests, home to the endemic Sri Lanka whistling thrush and sambar deer.",
    "bestTime": "January – March",
    "sightings": [
      "Sambar Deer",
      "Sri Lanka Whistling Thrushes",
      "Highland Leopards",
      "Giant Squirrels",
      "Tree Ferns"
    ],
    "packagesCount": 2,
    "startingPrice": 280
  },
  {
    "id": 65,
    "slug": "pigeon-island-national-park",
    "name": "Pigeon Island National Park",
    "country": "Sri Lanka",
    "region": "Trincomalee Coast",
    "category": "Island & Marine Reserves",
    "image": "/assets/images/destinations/pigeon-island-national-park.jpg",
    "badge": "Blacktip Reef Shark Haven",
    "tagline": "Vibrant coral reefs and guaranteed snorkeling with harmless Blacktip Reef Sharks",
    "desc": "One of Sri Lanka's premier marine parks featuring shallow coral gardens where dozens of juvenile and adult blacktip reef sharks cruise crystal waters.",
    "bestTime": "May – October",
    "sightings": [
      "Blacktip Reef Sharks",
      "Hawksbill Turtles",
      "Parrotfish",
      "Moray Eels",
      "Live Corals"
    ],
    "packagesCount": 2,
    "startingPrice": 260
  },
  {
    "id": 66,
    "slug": "pantanal-wetlands-brazil",
    "name": "Pantanal Matogrossense National Park",
    "country": "Brazil",
    "region": "South America",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/pantanal-wetlands-brazil.jpg",
    "badge": "Jaguar Paradise",
    "tagline": "The world's largest tropical wetland and highest jaguar density",
    "desc": "Vast flooded plains offering boat-based tracking along the Cuiabá and Three Brothers rivers to photograph apex jaguars hunting caimans on riverbanks.",
    "bestTime": "June – October",
    "sightings": [
      "Jaguars",
      "Giant River Otters",
      "Capybaras",
      "Hyacinth Macaws",
      "Yacare Caimans"
    ],
    "packagesCount": 4,
    "startingPrice": 850
  },
  {
    "id": 67,
    "slug": "amazon-rainforest-peru-ecuador",
    "name": "Amazon Rainforest (Yasuni & Tambopata)",
    "country": "Peru / Ecuador",
    "region": "South America",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/amazon-rainforest-peru-ecuador.jpg",
    "badge": "Global Biodiversity Heart",
    "tagline": "The greatest biodiversity on planet Earth along mighty tributaries",
    "desc": "Canopy walkways, clay mineral licks filled with thousands of vibrant macaws, pink river dolphins, and night nocturnal insect and reptile searches.",
    "bestTime": "May – October",
    "sightings": [
      "Pink River Dolphins",
      "Scarlet Macaws",
      "Harpy Eagles",
      "Black Caimans",
      "Howler Monkeys"
    ],
    "packagesCount": 4,
    "startingPrice": 680
  },
  {
    "id": 68,
    "slug": "tortuguero-national-park",
    "name": "Tortuguero National Park",
    "country": "Costa Rica",
    "region": "Central America",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/tortuguero-national-park.jpg",
    "badge": "Sea Turtle Haven",
    "tagline": "Caribbean coastal canals and premier nesting beaches of Green Sea Turtles",
    "desc": "A roadless wilderness reachable only by boat or plane, famous for misty river canals filled with sloths, toucans, and nesting sea turtles on Atlantic sands.",
    "bestTime": "July – October",
    "sightings": [
      "Green Sea Turtles",
      "Three-Toed Sloths",
      "Keel-billed Toucans",
      "Poison Dart Frogs",
      "Spider Monkeys"
    ],
    "packagesCount": 3,
    "startingPrice": 520
  },
  {
    "id": 69,
    "slug": "corcovado-national-park",
    "name": "Corcovado National Park",
    "country": "Costa Rica",
    "region": "Central America",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/corcovado-national-park.jpg",
    "badge": "Intense Biodiversity",
    "tagline": "Described by National Geographic as the most biologically intense place on Earth",
    "desc": "The crown jewel of Costa Rica's national parks, preserving ancient lowland rainforests, Baird's tapirs, jaguars, and scarlet macaws.",
    "bestTime": "December – April",
    "sightings": [
      "Baird's Tapirs",
      "Pumas",
      "Scarlet Macaws",
      "Bull Sharks",
      "Squirrel Monkeys"
    ],
    "packagesCount": 3,
    "startingPrice": 580
  },
  {
    "id": 70,
    "slug": "bwindi-gorilla-reserve",
    "name": "Bwindi Impenetrable National Park",
    "country": "Uganda",
    "region": "East Africa",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/bwindi-gorilla-reserve.jpg",
    "badge": "Mountain Gorillas",
    "tagline": "Trek the mist-shrouded ancient rainforest to meet endangered Mountain Gorillas",
    "desc": "A steep, primeval jungle sheltering half of the world's remaining Mountain Gorillas, vibrant birdlife, and rich biodiversity dating back over 25,000 years.",
    "bestTime": "June – September & Dec – Feb",
    "sightings": [
      "Mountain Gorillas",
      "Chimpanzees",
      "L'Hoest Monkeys",
      "African Green Broadbills",
      "Colobus Monkeys"
    ],
    "packagesCount": 4,
    "startingPrice": 890
  },
  {
    "id": 71,
    "slug": "tanjung-puting-borneo",
    "name": "Tanjung Puting National Park (Borneo)",
    "country": "Indonesia",
    "region": "Borneo",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/tanjung-puting-borneo.jpg",
    "badge": "Wild Orangutans",
    "tagline": "Cruise the Sekonyer River on a traditional wooden Klotok boat to meet Orangutans",
    "desc": "Ancient peat swamp forests where wild and rehabilitated Bornean orangutans swing through canopy, alongside proboscis monkeys and hornbills.",
    "bestTime": "June – September",
    "sightings": [
      "Bornean Orangutans",
      "Proboscis Monkeys",
      "Gibbons",
      "Sun Bears",
      "Hornbills"
    ],
    "packagesCount": 3,
    "startingPrice": 560
  },
  {
    "id": 72,
    "slug": "gunung-leuser-sumatra",
    "name": "Gunung Leuser National Park",
    "country": "Indonesia",
    "region": "Sumatra",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/gunung-leuser-sumatra.jpg",
    "badge": "Sumatran Giants",
    "tagline": "One of the last sanctuaries on Earth where Tigers, Elephants, Rhinos, and Orangutans coexist",
    "desc": "A vast UNESCO World Heritage rainforest in northern Sumatra renowned for jungle river trekking in Bukit Lawang to view semi-wild orangutans.",
    "bestTime": "May – September",
    "sightings": [
      "Sumatran Orangutans",
      "Thomas Leaf Monkeys",
      "Hornbills",
      "Sumatran Tigers",
      "Elephants"
    ],
    "packagesCount": 3,
    "startingPrice": 460
  },
  {
    "id": 73,
    "slug": "danum-valley-borneo",
    "name": "Danum Valley Conservation Area",
    "country": "Malaysia",
    "region": "Sabah (Borneo)",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/danum-valley-borneo.jpg",
    "badge": "130-Million-Year-Old Jungle",
    "tagline": "One of the world's most complex primary rainforests with canopy walkways",
    "desc": "Untouched lowland dipterocarp forest harboring Bornean pygmy elephants, clouded leopards, orangutans, and giant flying squirrels.",
    "bestTime": "March – October",
    "sightings": [
      "Bornean Pygmy Elephants",
      "Clouded Leopards",
      "Orangutans",
      "Red Leaf Monkeys",
      "Flying Squirrels"
    ],
    "packagesCount": 3,
    "startingPrice": 690
  },
  {
    "id": 74,
    "slug": "kinabatangan-river-reserve",
    "name": "Kinabatangan River Reserve",
    "country": "Malaysia",
    "region": "Sabah (Borneo)",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/kinabatangan-river-reserve.jpg",
    "badge": "Borneo River Safari",
    "tagline": "Boat safaris along Sabah's longest river to spot Proboscis Monkeys and Pygmy Elephants",
    "desc": "Flooded riverine corridors where boat safaris offer effortless views of pot-bellied proboscis monkeys leaping between branches at dusk.",
    "bestTime": "April – October",
    "sightings": [
      "Proboscis Monkeys",
      "Pygmy Elephants",
      "Crocodiles",
      "Rhinoceros Hornbills",
      "Storm's Storks"
    ],
    "packagesCount": 3,
    "startingPrice": 480
  },
  {
    "id": 75,
    "slug": "daintree-rainforest",
    "name": "Daintree Rainforest",
    "country": "Australia",
    "region": "Queensland",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/daintree-rainforest.jpg",
    "badge": "Oldest Tropical Rainforest",
    "tagline": "Where the 180-million-year-old rainforest meets the Great Barrier Reef",
    "desc": "Ancient living museum home to the prehistoric Southern Cassowary, estuarine crocodiles on the Daintree River, and ancient primitive flowering plants.",
    "bestTime": "May – November",
    "sightings": [
      "Southern Cassowaries",
      "Saltwater Crocodiles",
      "Tree Kangaroos",
      "Boyd's Forest Dragons",
      "Ulysses Butterflies"
    ],
    "packagesCount": 3,
    "startingPrice": 510
  },
  {
    "id": 76,
    "slug": "kakadu-national-park",
    "name": "Kakadu National Park",
    "country": "Australia",
    "region": "Northern Territory",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/kakadu-national-park.jpg",
    "badge": "Ancient Aboriginal Haven",
    "tagline": "65,000 years of Indigenous culture and giant saltwater crocodiles",
    "desc": "Vast wetlands, sandstone escarpments, and Yellow Water billabongs teeming with giant saltwater crocodiles, barramundi, and sea eagles.",
    "bestTime": "May – October",
    "sightings": [
      "Saltwater Crocodiles",
      "Brolgas",
      "Dingoes",
      "Wallabies",
      "Sea Eagles"
    ],
    "packagesCount": 3,
    "startingPrice": 530
  },
  {
    "id": 77,
    "slug": "manu-national-park",
    "name": "Manu National Park",
    "country": "Peru",
    "region": "Amazon Basin",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/manu-national-park.jpg",
    "badge": "Biosphere Pinnacle",
    "tagline": "From Andean cloud forests to pristine virgin Amazon lowlands",
    "desc": "One of the most pristine reserves on Earth spanning from 4,000m Andean plateaus down to lowland oxbow lakes filled with giant river otters and jaguars.",
    "bestTime": "May – October",
    "sightings": [
      "Jaguars",
      "Giant River Otters",
      "Cock-of-the-Rocks",
      "Black Caimans",
      "Emperor Tamarins"
    ],
    "packagesCount": 3,
    "startingPrice": 790
  },
  {
    "id": 78,
    "slug": "murchison-falls-reserve",
    "name": "Murchison Falls National Park",
    "country": "Uganda",
    "region": "East Africa",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/murchison-falls-reserve.jpg",
    "badge": "Roaring Nile",
    "tagline": "Where the mighty Nile forces through a 7-meter gorge with thunderous power",
    "desc": "Uganda's oldest conservation area, combining thrilling boat safaris to the base of the falls with game drives for Rothschild giraffes and lions.",
    "bestTime": "December – February & June – September",
    "sightings": [
      "Rothschild Giraffes",
      "Elephants",
      "Lions",
      "Shoebill Storks",
      "Hippos"
    ],
    "packagesCount": 3,
    "startingPrice": 590
  },
  {
    "id": 79,
    "slug": "everglades-national-park",
    "name": "Everglades National Park",
    "country": "USA",
    "region": "Florida",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/everglades-national-park.jpg",
    "badge": "River of Grass",
    "tagline": "Vast subtropical wilderness where Alligators and Crocodiles coexist",
    "desc": "A 1.5-million-acre wetland ecosystem traversed by airboat and kayak, home to American alligators, manatees, and Florida panthers.",
    "bestTime": "December – April",
    "sightings": [
      "American Alligators",
      "West Indian Manatees",
      "Florida Panthers",
      "Roseate Spoonbills",
      "Ospreys"
    ],
    "packagesCount": 2,
    "startingPrice": 340
  },
  {
    "id": 80,
    "slug": "monteverde-cloud-forest",
    "name": "Monteverde Cloud Forest Reserve",
    "country": "Costa Rica",
    "region": "Central America",
    "category": "Wetlands & Rainforests",
    "image": "/assets/images/destinations/monteverde-cloud-forest.jpg",
    "badge": "Misty Canopy",
    "tagline": "Highland mist draped in orchids and home to the Resplendent Quetzal",
    "desc": "A renowned cloud forest straddling the Continental Divide with suspended hanging bridges and vibrant hummingbirds.",
    "bestTime": "December – May",
    "sightings": [
      "Resplendent Quetzals",
      "Two-toed Sloths",
      "Hummingbirds",
      "Howler Monkeys",
      "Glass Frogs"
    ],
    "packagesCount": 3,
    "startingPrice": 390
  },
  {
    "id": 81,
    "slug": "svalbard-polar-bear-arctic",
    "name": "Svalbard Archipelago & Spitsbergen",
    "country": "Norway",
    "region": "High Arctic",
    "category": "Polar & Arctic Tundras",
    "image": "/assets/images/destinations/svalbard-polar-bear-arctic.jpg",
    "badge": "Kingdom of the Polar Bear",
    "tagline": "Glacial fjords and pack ice ruled by the King of the Arctic",
    "desc": "High Arctic wilderness at 78° North, where ice-strengthened expedition ships cruise frozen pack ice to view polar bears, walruses, and beluga whales.",
    "bestTime": "June – August",
    "sightings": [
      "Polar Bears",
      "Walruses",
      "Beluga Whales",
      "Arctic Foxes",
      "Reindeer"
    ],
    "packagesCount": 4,
    "startingPrice": 1250
  },
  {
    "id": 82,
    "slug": "churchill-polar-bear-capital",
    "name": "Churchill Polar Bear Capital",
    "country": "Canada",
    "region": "Manitoba",
    "category": "Polar & Arctic Tundras",
    "image": "/assets/images/destinations/churchill-polar-bear-capital.jpg",
    "badge": "Polar Bear Gathering",
    "tagline": "Custom Tundra Buggies tracking polar bears waiting for Hudson Bay to freeze",
    "desc": "Every autumn, hundreds of polar bears gather on the shores of Hudson Bay, sparring in the snow and interacting close to custom heated tundra rovers.",
    "bestTime": "October – November",
    "sightings": [
      "Polar Bears",
      "Arctic Hares",
      "Snowy Owls",
      "Arctic Foxes",
      "Ptarmigans"
    ],
    "packagesCount": 3,
    "startingPrice": 980
  },
  {
    "id": 83,
    "slug": "katmai-brown-bear-reserve",
    "name": "Katmai National Park & Brooks Falls",
    "country": "USA",
    "region": "Alaska",
    "category": "Polar & Arctic Tundras",
    "image": "/assets/images/destinations/katmai-brown-bear-reserve.jpg",
    "badge": "Brown Bear Salmon Catch",
    "tagline": "Giant coastal brown bears catching leaping sockeye salmon at Brooks Falls",
    "desc": "Accessible only by floatplane, Katmai features viewing platforms overlooking Brooks Falls where world's largest brown bears compete for leaping salmon.",
    "bestTime": "July – September",
    "sightings": [
      "Grizzly / Brown Bears",
      "Bald Eagles",
      "Sockeye Salmon",
      "Moose",
      "River Otters"
    ],
    "packagesCount": 3,
    "startingPrice": 870
  },
  {
    "id": 84,
    "slug": "denali-national-park-alaska",
    "name": "Denali National Park & Preserve",
    "country": "USA",
    "region": "Alaska",
    "category": "Polar & Arctic Tundras",
    "image": "/assets/images/destinations/denali-national-park-alaska.jpg",
    "badge": "Subarctic Tundra",
    "tagline": "Six million acres of wild subarctic taiga beneath North America's highest peak",
    "desc": "A road-limited wilderness where solitary grizzly bears, caribou herds, Dall sheep, and moose wander beneath 20,310-foot Mount Denali.",
    "bestTime": "June – September",
    "sightings": [
      "Grizzly Bears",
      "Moose",
      "Caribou",
      "Dall Sheep",
      "Gray Wolves"
    ],
    "packagesCount": 3,
    "startingPrice": 620
  },
  {
    "id": 85,
    "slug": "yellowstone-national-park",
    "name": "Yellowstone National Park",
    "country": "USA",
    "region": "Wyoming / Montana",
    "category": "Polar & Arctic Tundras",
    "image": "/assets/images/destinations/yellowstone-national-park.jpg",
    "badge": "Serengeti of North America",
    "tagline": "Geothermal geysers and Lamar Valley wolf packs & bison herds",
    "desc": "America's first national park, featuring geothermal hot springs, roaring geysers, and the Lamar Valley where wild wolf packs, grizzly bears, and bison roam.",
    "bestTime": "May – October & Winter Wolves",
    "sightings": [
      "Gray Wolves",
      "Bison Herds",
      "Grizzly Bears",
      "Elk",
      "Bighorn Sheep"
    ],
    "packagesCount": 4,
    "startingPrice": 620
  },
  {
    "id": 86,
    "slug": "wrangell-st-elias-park",
    "name": "Wrangell-St. Elias National Park",
    "country": "USA",
    "region": "Alaska",
    "category": "Polar & Arctic Tundras",
    "image": "/assets/images/destinations/wrangell-st-elias-park.jpg",
    "badge": "America's Largest Park",
    "tagline": "13.2 million acres of mammoth glaciers, icefields, and historic copper mines",
    "desc": "Equal in size to six Yellowstones combined, home to massive glaciers, Dall sheep clinging to rocky crags, and backcountry wilderness.",
    "bestTime": "June – August",
    "sightings": [
      "Dall Sheep",
      "Grizzly Bears",
      "Mountain Goats",
      "Caribou",
      "Wolverines"
    ],
    "packagesCount": 2,
    "startingPrice": 750
  },
  {
    "id": 87,
    "slug": "pacific-rim-national-park",
    "name": "Pacific Rim National Park Reserve",
    "country": "Canada",
    "region": "Vancouver Island",
    "category": "Polar & Arctic Tundras",
    "image": "/assets/images/destinations/pacific-rim-national-park.jpg",
    "badge": "Rainforest & Ocean",
    "tagline": "Temperate coastal rainforests and Pacific Gray Whale migration trails",
    "desc": "Wild windswept beaches and ancient temperate cedar rainforests where black bears forage on the shoreline and gray whales spout in coastal bays.",
    "bestTime": "March – October",
    "sightings": [
      "Gray Whales",
      "Orcas",
      "Coastal Black Bears",
      "Bald Eagles",
      "Sea Otters"
    ],
    "packagesCount": 3,
    "startingPrice": 580
  },
  {
    "id": 88,
    "slug": "kenai-fjords-national-park",
    "name": "Kenai Fjords National Park",
    "country": "USA",
    "region": "Alaska",
    "category": "Polar & Arctic Tundras",
    "image": "/assets/images/destinations/kenai-fjords-national-park.jpg",
    "badge": "Tidewater Glaciers",
    "tagline": "Calving tidewater glaciers, orca pods, and puffin rookeries",
    "desc": "Where the Harding Icefield crowns coastal fjords, offering catamaran cruises past crashing icebergs filled with sea otters, harbor seals, and orcas.",
    "bestTime": "May – September",
    "sightings": [
      "Orcas (Killer Whales)",
      "Humpback Whales",
      "Puffins",
      "Sea Otters",
      "Harbor Seals"
    ],
    "packagesCount": 3,
    "startingPrice": 640
  },
  {
    "id": 89,
    "slug": "south-georgia-antarctica",
    "name": "South Georgia & Antarctic Peninsula",
    "country": "Antarctica / UK Territory",
    "region": "Southern Ocean",
    "category": "Polar & Arctic Tundras",
    "image": "/assets/images/destinations/south-georgia-antarctica.jpg",
    "badge": "King Penguin Megacolonies",
    "tagline": "Hundreds of thousands of King Penguins and colossal iceberg cathedrals",
    "desc": "The Serengeti of the Southern Ocean, where Salisbury Plain and St. Andrews Bay host colonies of over 300,000 king penguins and elephant seals.",
    "bestTime": "November – March",
    "sightings": [
      "King Penguins",
      "Elephant Seals",
      "Humpback Whales",
      "Leopard Seals",
      "Wandering Albatrosses"
    ],
    "packagesCount": 3,
    "startingPrice": 1850
  },
  {
    "id": 90,
    "slug": "ellesmere-island-arctic",
    "name": "Ellesmere Island Arctic Reserve (Quttinirpaaq)",
    "country": "Canada",
    "region": "Nunavut (High Arctic)",
    "category": "Polar & Arctic Tundras",
    "image": "/assets/images/destinations/ellesmere-island-arctic.jpg",
    "badge": "Top of the World",
    "tagline": "North America's northernmost park with pure white Arctic Wolves and Muskoxen",
    "desc": "A polar desert at 82° North where midnight sun illuminates herds of prehistoric muskoxen and fearless white Arctic wolves.",
    "bestTime": "June – July",
    "sightings": [
      "Arctic Wolves",
      "Muskoxen",
      "Peary Caribou",
      "Arctic Hares",
      "Gyrfalcons"
    ],
    "packagesCount": 2,
    "startingPrice": 1450
  },
  {
    "id": 91,
    "slug": "galapagos-islands",
    "name": "Galapagos Islands National Park",
    "country": "Ecuador",
    "region": "Pacific Ocean",
    "category": "Island & Marine Reserves",
    "image": "/assets/images/destinations/galapagos-islands.jpg",
    "badge": "Evolutionary Sanctuary",
    "tagline": "Darwin's living laboratory of fearless, endemic wildlife",
    "desc": "Volcanic archipelago in the Pacific where marine iguanas dive for algae, giant tortoises roam volcanic highlands, and sea lions swim with snorkelers.",
    "bestTime": "Year-round",
    "sightings": [
      "Galapagos Giant Tortoises",
      "Marine Iguanas",
      "Blue-Footed Boobies",
      "Sea Lions",
      "Galapagos Penguins"
    ],
    "packagesCount": 4,
    "startingPrice": 1100
  },
  {
    "id": 92,
    "slug": "great-barrier-reef-reserve",
    "name": "Great Barrier Reef Marine Park",
    "country": "Australia",
    "region": "Queensland",
    "category": "Island & Marine Reserves",
    "image": "/assets/images/destinations/great-barrier-reef-reserve.jpg",
    "badge": "World's Largest Coral Reef",
    "tagline": "Over 2,300 kilometers of vibrant coral cays and marine biodiversity",
    "desc": "The largest living structure on Earth, home to green sea turtles, manta rays, reef sharks, and thousands of vivid tropical fish species.",
    "bestTime": "June – November",
    "sightings": [
      "Green Sea Turtles",
      "Manta Rays",
      "Reef Sharks",
      "Clownfish",
      "Humpback Whales"
    ],
    "packagesCount": 4,
    "startingPrice": 650
  },
  {
    "id": 93,
    "slug": "ningaloo-marine-park",
    "name": "Ningaloo Marine Park",
    "country": "Australia",
    "region": "Western Australia",
    "category": "Island & Marine Reserves",
    "image": "/assets/images/destinations/ningaloo-marine-park.jpg",
    "badge": "Whale Shark Swim",
    "tagline": "Fringing coral reef where you can swim alongside giant Whale Sharks",
    "desc": "A pristine reef accessible right from the beach, where spotter planes guide snorkelers into the water alongside gentle 12-meter whale sharks and manta rays.",
    "bestTime": "March – August",
    "sightings": [
      "Whale Sharks",
      "Manta Rays",
      "Humpback Whales",
      "Dugongs",
      "Loggerhead Turtles"
    ],
    "packagesCount": 3,
    "startingPrice": 710
  },
  {
    "id": 94,
    "slug": "komodo-national-park",
    "name": "Komodo National Park",
    "country": "Indonesia",
    "region": "Lesser Sunda Islands",
    "category": "Island & Marine Reserves",
    "image": "/assets/images/destinations/komodo-national-park.jpg",
    "badge": "Living Dragons",
    "tagline": "The world's largest living lizard and kaleidoscopic coral reefs",
    "desc": "Arid savannah islands surrounded by rich marine currents where 3-meter Komodo dragons hunt deer, alongside manta ray cleaning stations and pink sand beaches.",
    "bestTime": "April – November",
    "sightings": [
      "Komodo Dragons",
      "Manta Rays",
      "Timor Deer",
      "Sea Turtles",
      "Dolphins"
    ],
    "packagesCount": 4,
    "startingPrice": 580
  },
  {
    "id": 95,
    "slug": "raja-ampat-marine-park",
    "name": "Raja Ampat Marine Park",
    "country": "Indonesia",
    "region": "West Papua",
    "category": "Island & Marine Reserves",
    "image": "/assets/images/destinations/raja-ampat-marine-park.jpg",
    "badge": "Coral Triangle Crown",
    "tagline": "The world's richest marine biodiversity with 75% of all known coral species",
    "desc": "Karst limestone islands rising from sapphire waters, home to pygmy seahorses, wobbegong sharks, manta rays, and pristine coral gardens.",
    "bestTime": "October – April",
    "sightings": [
      "Manta Rays",
      "Wobbegong Sharks",
      "Pygmy Seahorses",
      "Green Sea Turtles",
      "Birds of Paradise"
    ],
    "packagesCount": 3,
    "startingPrice": 990
  },
  {
    "id": 96,
    "slug": "kaikoura-whale-sanctuary-nz",
    "name": "Kaikoura Marine Sanctuary",
    "country": "New Zealand",
    "region": "South Island",
    "category": "Island & Marine Reserves",
    "image": "/assets/images/destinations/kaikoura-whale-sanctuary-nz.jpg",
    "badge": "Giant Sperm Whales",
    "tagline": "Deep ocean trenches plunging off coastal alpine mountains",
    "desc": "A two-kilometer-deep marine canyon close to shore creates rich upwellings attracting resident giant sperm whales, dusky dolphins, and albatrosses year-round.",
    "bestTime": "Year-round (Oct – Mar best)",
    "sightings": [
      "Giant Sperm Whales",
      "Dusky Dolphins",
      "Fur Seals",
      "Wandering Albatrosses",
      "Orcas"
    ],
    "packagesCount": 3,
    "startingPrice": 470
  },
  {
    "id": 97,
    "slug": "andasibe-mantadia-madagascar",
    "name": "Andasibe-Mantadia National Park",
    "country": "Madagascar",
    "region": "Indian Ocean",
    "category": "Island & Marine Reserves",
    "image": "/assets/images/destinations/andasibe-mantadia-madagascar.jpg",
    "badge": "Land of the Lemurs",
    "tagline": "Hear the haunting wail of the giant Indri Lemur in misty montane rainforest",
    "desc": "Pristine rainforest sheltering the Indri (largest living lemur), diademed sifakas, leaf-tailed geckos, and vivid chameleons found nowhere else on Earth.",
    "bestTime": "September – January",
    "sightings": [
      "Indri Lemurs",
      "Diademed Sifakas",
      "Parson's Chameleons",
      "Aye-Ayes",
      "Fossas"
    ],
    "packagesCount": 3,
    "startingPrice": 540
  },
  {
    "id": 98,
    "slug": "kangaroo-island-wildlife-sanctuary",
    "name": "Kangaroo Island Wildlife Sanctuary",
    "country": "Australia",
    "region": "South Australia",
    "category": "Island & Marine Reserves",
    "image": "/assets/images/destinations/kangaroo-island-wildlife-sanctuary.jpg",
    "badge": "Australia's Galapagos",
    "tagline": "Untamed coastal sanctuary for kangaroos, koalas, and sea lion colonies",
    "desc": "Separated from mainland Australia, preserving pristine populations of Kangaroo Island kangaroos, wild koalas in eucalyptus groves, and sea lions at Seal Bay.",
    "bestTime": "October – April",
    "sightings": [
      "Kangaroos",
      "Koalas",
      "Australian Sea Lions",
      "Echidnas",
      "Fairy Penguins"
    ],
    "packagesCount": 3,
    "startingPrice": 480
  },
  {
    "id": 99,
    "slug": "monterey-bay-marine-sanctuary",
    "name": "Monterey Bay National Marine Sanctuary",
    "country": "USA",
    "region": "California",
    "category": "Island & Marine Reserves",
    "image": "/assets/images/destinations/monterey-bay-marine-sanctuary.jpg",
    "badge": "Deep Submarine Canyon",
    "tagline": "Giant Blue Whales, Humpbacks, and playful Sea Otters along the Big Sur coast",
    "desc": "A massive underwater canyon descending over 3,000 meters that fuels rich nutrient upwellings, attracting blue whales, killer whales, and playful sea otters.",
    "bestTime": "April – November",
    "sightings": [
      "Blue Whales",
      "Humpback Whales",
      "Southern Sea Otters",
      "Orcas",
      "Risso's Dolphins"
    ],
    "packagesCount": 2,
    "startingPrice": 390
  },
  {
    "id": 100,
    "slug": "shark-bay-world-heritage",
    "name": "Shark Bay World Heritage Area",
    "country": "Australia",
    "region": "Western Australia",
    "category": "Island & Marine Reserves",
    "image": "/assets/images/destinations/shark-bay-world-heritage.jpg",
    "badge": "Monkey Mia Dolphins",
    "tagline": "Pristine turquoise lagoons, stromatolites, and friendly wild Bottlenose Dolphins",
    "desc": "Ancient living stromatolites at Hamelin Pool, Shell Beach made of billions of cockle shells, and wild dolphins that swim to the shallows of Monkey Mia.",
    "bestTime": "May – October",
    "sightings": [
      "Bottlenose Dolphins",
      "Dugongs",
      "Tiger Sharks",
      "Loggerhead Turtles",
      "Emu Herds"
    ],
    "packagesCount": 2,
    "startingPrice": 460
  },
  {
    "id": 101,
    "slug": "hemis-national-park",
    "name": "Hemis National Park",
    "country": "India",
    "region": "Ladakh (High Himalayas)",
    "category": "Mountain & High Altitude",
    "image": "/assets/images/destinations/hemis-national-park.jpg",
    "badge": "Snow Leopard Capital",
    "tagline": "High-altitude winter telemetry tracking the elusive 'Ghost of the Mountains'",
    "desc": "Rugged Trans-Himalayan valleys at 4,000+ meters elevation, where expert Ladakhi spotters track wild snow leopards, blue sheep, and Tibetan wolves.",
    "bestTime": "December – March",
    "sightings": [
      "Snow Leopards",
      "Blue Sheep (Bharal)",
      "Tibetan Wolves",
      "Golden Eagles",
      "Tibetan Ibex"
    ],
    "packagesCount": 3,
    "startingPrice": 750
  },
  {
    "id": 102,
    "slug": "volcanoes-national-park-rwanda",
    "name": "Volcanoes National Park",
    "country": "Rwanda",
    "region": "East Africa",
    "category": "Mountain & High Altitude",
    "image": "/assets/images/destinations/volcanoes-national-park-rwanda.jpg",
    "badge": "Dian Fossey Sanctuary",
    "tagline": "Bamboo slopes and volcanic peaks home to Golden Monkeys and Mountain Gorillas",
    "desc": "Five towering extinct volcanoes draped in bamboo forests where Dian Fossey pioneered gorilla conservation, offering world-class luxury eco-trekking.",
    "bestTime": "June – September & Dec – Feb",
    "sightings": [
      "Mountain Gorillas",
      "Golden Monkeys",
      "Forest Elephants",
      "Bushbucks",
      "Spotted Hyenas"
    ],
    "packagesCount": 3,
    "startingPrice": 950
  },
  {
    "id": 103,
    "slug": "torres-del-paine-patagonia",
    "name": "Torres del Paine National Park",
    "country": "Chile",
    "region": "Patagonia",
    "category": "Mountain & High Altitude",
    "image": "/assets/images/destinations/torres-del-paine-patagonia.jpg",
    "badge": "Patagonian Puma Haven",
    "tagline": "Glacial granite horns and the world's premier wild Puma tracking grounds",
    "desc": "Dramatic turquoise lakes, hanging glaciers, and windswept pampas where expert trackers spot wild Patagonian pumas hunting guanaco herds.",
    "bestTime": "November – April",
    "sightings": [
      "Patagonian Pumas",
      "Guanacos",
      "Andean Condors",
      "Culpeo Foxes",
      "Flamingos"
    ],
    "packagesCount": 3,
    "startingPrice": 890
  },
  {
    "id": 104,
    "slug": "banff-jasper-rockies",
    "name": "Banff & Jasper National Parks",
    "country": "Canada",
    "region": "Canadian Rockies",
    "category": "Mountain & High Altitude",
    "image": "/assets/images/destinations/banff-jasper-rockies.jpg",
    "badge": "Glacial Wilderness",
    "tagline": "Turquoise glacial lakes and alpine wildlife beneath towering Rocky peaks",
    "desc": "Pristine Rocky Mountain corridors along the Icefields Parkway where black bears, elk, bighorn sheep, and mountain goats roam glaciated valleys.",
    "bestTime": "June – September",
    "sightings": [
      "Grizzly Bears",
      "Black Bears",
      "Elk",
      "Bighorn Sheep",
      "Mountain Goats"
    ],
    "packagesCount": 3,
    "startingPrice": 590
  },
  {
    "id": 105,
    "slug": "simien-mountains-ethiopia",
    "name": "Simien Mountains National Park",
    "country": "Ethiopia",
    "region": "East Africa",
    "category": "Mountain & High Altitude",
    "image": "/assets/images/destinations/simien-mountains-ethiopia.jpg",
    "badge": "Roof of Africa",
    "tagline": "Jagged volcanic escarpments home to Gelada Baboons and Walia Ibex",
    "desc": "Dramatic gorges plunging 1,500 meters, where thousands of herbivorous Gelada baboons forage on alpine plateaus alongside Ethiopian wolves.",
    "bestTime": "October – April",
    "sightings": [
      "Gelada Baboons",
      "Walia Ibex",
      "Ethiopian Wolves",
      "Bearded Vultures",
      "Klipspringers"
    ],
    "packagesCount": 3,
    "startingPrice": 620
  },
  {
    "id": 106,
    "slug": "bale-mountains-ethiopia",
    "name": "Bale Mountains National Park",
    "country": "Ethiopia",
    "region": "Horn of Africa",
    "category": "Mountain & High Altitude",
    "image": "/assets/images/destinations/bale-mountains-ethiopia.jpg",
    "badge": "Ethiopian Wolf Haven",
    "tagline": "Afro-alpine Sanetti Plateau sheltering the world's rarest canid",
    "desc": "High alpine plateau at 4,000m altitude and Harenna cloud forest sheltering over half of the surviving wild population of critically endangered Ethiopian Wolves.",
    "bestTime": "November – March",
    "sightings": [
      "Ethiopian Wolves",
      "Mountain Nyala",
      "Giant Mole-rats",
      "Menelik's Bushbucks",
      "Augur Buzzards"
    ],
    "packagesCount": 2,
    "startingPrice": 640
  },
  {
    "id": 107,
    "slug": "los-glaciares-fitz-roy",
    "name": "Los Glaciares National Park (Fitz Roy)",
    "country": "Argentina",
    "region": "Patagonia",
    "category": "Mountain & High Altitude",
    "image": "/assets/images/destinations/los-glaciares-fitz-roy.jpg",
    "badge": "Perito Moreno Glacier",
    "tagline": "Colossal calving ice walls and the soaring granite fangs of Mount Fitz Roy",
    "desc": "A stunning UNESCO wilderness of thunderous advancing glaciers, emerald meltwater lagoons, and Patagonian huemul deer.",
    "bestTime": "November – April",
    "sightings": [
      "Andean Condors",
      "Huemul Deer",
      "Patagonian Pumas",
      "Guanacos",
      "Torrent Ducks"
    ],
    "packagesCount": 3,
    "startingPrice": 720
  },
  {
    "id": 108,
    "slug": "fiordland-milford-sound-nz",
    "name": "Fiordland National Park (Milford Sound)",
    "country": "New Zealand",
    "region": "South Island",
    "category": "Mountain & High Altitude",
    "image": "/assets/images/destinations/fiordland-milford-sound-nz.jpg",
    "badge": "Eighth Wonder of the World",
    "tagline": "Sheer fiords rising out of dark waters with cascading waterfalls and Fiordland Crested Penguins",
    "desc": "Towering granite peaks carved by glaciers plunging thousands of feet into tranquil fjords where rare crested penguins and dolphins swim.",
    "bestTime": "November – April",
    "sightings": [
      "Fiordland Crested Penguins",
      "Bottlenose Dolphins",
      "New Zealand Fur Seals",
      "Kea Parrots",
      "Blue Ducks"
    ],
    "packagesCount": 3,
    "startingPrice": 590
  }
];
